In [1]:
import os
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import time
os.chdir(r"C:\Users\Aniket\Desktop\INTENTION")
x_train=np.load('X_train_ML.npy')
y_train=np.load('Y_train_ML.npy')
x_vel=np.load("X_vel_ML.npy")
y_vel=np.load("Y_vel_ML.npy")
min_m=np.load("min_m_ML.npy")
max_m=np.load("max_m_ML.npy")


In [2]:
shape=x_train.shape
print("input shape:",shape)
Shapey=y_train.shape
print("output shape:",y_train.shape)
print("x_vel.shape",x_vel.shape)
print("y_vel.shape",y_vel.shape)
print("min_m.shape",min_m.shape)
print("max_m.shape",max_m.shape)

input shape: (129040, 500)
output shape: (129040, 75)
x_vel.shape (32261, 100, 5)
y_vel.shape (32261, 15, 5)
min_m.shape (1, 1, 5)
max_m.shape (1, 1, 5)


In [8]:

import numpy as np
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Conv1D, MaxPooling1D, Flatten, Dense, Reshape
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_squared_error, r2_score,mean_absolute_error

x_train_split, x_test_split, y_train_split, y_test_split = train_test_split(x_train, y_train, test_size=0.2, random_state=42)
model = Sequential()
model.add(Reshape((500, 1), input_shape=(500,)))
model.add(Conv1D(filters=32, kernel_size=3, activation='relu'))
model.add(MaxPooling1D(pool_size=2))
model.add(Flatten())
model.add(Dense(64, activation='relu'))
model.add(Dense(32, activation='relu'))
model.add(Dense(32, activation='relu'))
model.add(Dense(32, activation='relu'))
model.add(Dense(32, activation='relu'))

model.add(Dense(75))
model.compile(optimizer='adam', loss='mean_squared_error')
model.summary()
model.fit(x_train_split, y_train_split, epochs=10, batch_size=32, validation_split=0.2)
y_pred = model.predict(x_train_split)



Model: "sequential_1"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 reshape_1 (Reshape)         (None, 500, 1)            0         
                                                                 
 conv1d_1 (Conv1D)           (None, 498, 32)           128       
                                                                 
 max_pooling1d_1 (MaxPoolin  (None, 249, 32)           0         
 g1D)                                                            
                                                                 
 flatten_1 (Flatten)         (None, 7968)              0         
                                                                 
 dense_6 (Dense)             (None, 64)                510016    
                                                                 
 dense_7 (Dense)             (None, 32)                2080      
                                                      

In [9]:
# ... (previous code for model definition and compilation)

# Assuming you have already trained the model using `x_train_split` and `y_train_split`.
# If not, you can train the model using `model.fit(x_train_split, y_train_split, epochs=epochs, batch_size=batch_size)`

# Predict the target values on the training set
y_train_pred = model.predict(x_train_split)

# Calculate the Mean Squared Error (MSE)
mse_train = mean_squared_error(y_train_split, y_train_pred)

# Calculate the Mean Absolute Error (MAE)
mae_train = mean_absolute_error(y_train_split, y_train_pred)

# Calculate the R-squared (R2)
r2_train = r2_score(y_train_split, y_train_pred)

# Print the results
print("Mean Squared Error (MSE) for train dataset:", mse_train)
print("Mean Absolute Error (MAE) for train dataset:", mae_train)
print("R-squared (R2) for train dataset:", r2_train)


3226/3226 [==============================] - 5s 2ms/step
Mean Squared Error (MSE) for train dataset: 1.7275845798925786
Mean Absolute Error (MAE) for train dataset: 0.7353979927140323
R-squared (R2) for train dataset: 0.6438643959377918


In [ ]:

history = model.fit(x_train_split, y_train_split, epochs=100, batch_size=32, validation_split=0.2)
train_loss = history.history['loss']
val_loss = history.history['val_loss']
epochs = range(1, len(train_loss) + 1)
plt.plot(epochs, train_loss, 'b', label='Training Loss')
plt.plot(epochs, val_loss, 'r', label='Validation Loss')
plt.title('Training and Validation Loss')
plt.xlabel('Epochs')
plt.ylabel('Loss')
plt.legend()
plt.show()



NameError: name 'history' is not defined

In [34]:
start_time = time.time()
model.fit(x_train_split, y_train_split, epochs=10, batch_size=32, validation_split=0.2)
end_time = time.time()
training_time = end_time - start_time
print(f"Training time: {training_time:.2f} seconds")

Epoch 1/10
2581/2581 [==============================] - 23s 9ms/step - loss: 1.3986 - val_loss: 1.5313
Epoch 2/10
2581/2581 [==============================] - 22s 9ms/step - loss: 1.3967 - val_loss: 1.5619
Epoch 3/10
2581/2581 [==============================] - 22s 9ms/step - loss: 1.3967 - val_loss: 1.5437
Epoch 4/10
2581/2581 [==============================] - 22s 9ms/step - loss: 1.3954 - val_loss: 1.5503
Epoch 5/10
2581/2581 [==============================] - 22s 9ms/step - loss: 1.3953 - val_loss: 1.6342
Epoch 6/10
2581/2581 [==============================] - 23s 9ms/step - loss: 1.3915 - val_loss: 1.5806
Epoch 7/10
2581/2581 [==============================] - 22s 9ms/step - loss: 1.3922 - val_loss: 1.5807
Epoch 8/10
2581/2581 [==============================] - 23s 9ms/step - loss: 1.3926 - val_loss: 1.5683
Epoch 9/10
2581/2581 [==============================] - 23s 9ms/step - loss: 1.3907 - val_loss: 1.5666
Epoch 10/10
2581/2581 [==============================] - 22s 9ms/step - l

In [8]:
import psutil

def get_memory_used():
    process = psutil.Process()
    memory_info = process.memory_info()
    memory_used = memory_info.rss  # Resident Set Size (non-swapped physical memory usage)
    return memory_used

if __name__ == "__main__":
    memory_used = get_memory_used()
    print(f"Memory Used: {memory_used} bytes")


Memory Used: 2037846016 bytes


In [35]:
import numpy as np

# Assuming you have already trained the model and made predictions on x_test_split
y_pred = model.predict(x_test_split)

# Calculate the standard deviation of the predictions
std_deviation = np.std(y_pred)

print("Standard Deviation of Predictions:", std_deviation)


807/807 [==============================] - 2s 2ms/step
Standard Deviation of Predictions: 2.1405911


In [36]:
from sklearn.metrics import mean_squared_error, r2_score,mean_absolute_error
print(mean_absolute_error(y_test_split, y_pred))

0.7161777521537259


In [37]:
print("shape of min_m:",min_m.shape)
min_m_reshape=min_m.reshape(-1,5)
print("min_m_reshape=",min_m_reshape.shape)
max_m_reshape=max_m.reshape(-1,5)
print("max_m_reshape=",max_m_reshape.shape)

shape of min_m: (1, 1, 5)
min_m_reshape= (1, 5)
max_m_reshape= (1, 5)


In [38]:
x_test12=np.load('x_in12.npy')
y_test12=np.load('y_op12.npy')
print("x_test12.shape:",x_test12.shape)
print("y_test12.shape:",y_test12.shape)

x_test12.shape: (16046, 100, 5)
y_test12.shape: (16046, 15, 5)


In [39]:
x_norm=(x_test12-min_m_reshape)/(max_m_reshape-min_m_reshape)
print(x_norm)

[[[0.3827419  0.51593461 0.4018613  0.45883533 0.50436771]
  [0.38202139 0.51656545 0.40224799 0.45907565 0.50400144]
  [0.38245823 0.51746373 0.40222012 0.45895361 0.50456772]
  ...
  [0.39219826 0.51257151 0.40065783 0.45382585 0.49483494]
  [0.39106777 0.50947188 0.40130774 0.45306802 0.49664447]
  [0.38750032 0.50947963 0.40153741 0.45196297 0.4995851 ]]

 [[0.38202139 0.51656545 0.40224799 0.45907565 0.50400144]
  [0.38245823 0.51746373 0.40222012 0.45895361 0.50456772]
  [0.38202444 0.51787686 0.40220234 0.45883839 0.50465072]
  ...
  [0.39106777 0.50947188 0.40130774 0.45306802 0.49664447]
  [0.38750032 0.50947963 0.40153741 0.45196297 0.4995851 ]
  [0.38472053 0.51065097 0.40160003 0.45089831 0.5050765 ]]

 [[0.38245823 0.51746373 0.40222012 0.45895361 0.50456772]
  [0.38202444 0.51787686 0.40220234 0.45883839 0.50465072]
  [0.38244254 0.51851574 0.40217068 0.45895275 0.50404554]
  ...
  [0.38750032 0.50947963 0.40153741 0.45196297 0.4995851 ]
  [0.38472053 0.51065097 0.4016000

In [40]:
x_test12_reshape= x_test12.reshape(-1, 500)
print("x_test12_reshape shape:",x_test12_reshape.shape)
y_test12_reshape= y_test12.reshape(-1, 75)
print("y_test12_reshape shape:",y_test12_reshape.shape)

x_test12_reshape shape: (16046, 500)
y_test12_reshape shape: (16046, 75)


In [41]:
y_pred_test = model.predict(x_test12_reshape)

502/502 [==============================] - 1s 2ms/step


In [42]:
from sklearn.metrics import r2_score
from sklearn.metrics import mean_squared_error
from sklearn.metrics import mean_absolute_error

print(mean_squared_error(y_test12_reshape,y_pred_test))
print(r2_score(y_test12_reshape,y_pred_test))
print(mean_absolute_error(y_test12_reshape,y_pred_test))

13489.059476007098
-4668.013608997836
93.436795055066


In [43]:
import numpy as np

# Assuming you have already trained the model and made predictions on x_test_split
y_pred = model.predict(x_test12_reshape)

# Calculate the standard deviation of the predictions
std_deviation = np.std(y_pred_test)

print("Standard Deviation of Predictions:", std_deviation)

502/502 [==============================] - 1s 2ms/step
Standard Deviation of Predictions: 117.28798
