In [2]:
import os
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import numpy as np

os.chdir(r"C:\Users\Aniket\Desktop\INTENTION")

xin=np.load('x_incom.npy')
y_op=np.load('y_opcom.npy')
print("xin.shape",xin.shape)
print("y_op.shape",y_op.shape)


xin.shape (161301, 100, 5)
y_op.shape (161301, 15, 5)


In [3]:
In=xin[0:3,:]
Op=y_op[0:3,:]
print("In",In)
print("Op",Op)
def shuffle(inp,tar):
    m=inp.shape[0]
    #print("m",m)
    perm=np.random.permutation(m)
    #print("perm",perm)
    inp=inp[perm,:]
    tar=tar[perm,:]
    return inp, tar
Ins,Ops=shuffle(In,Op)
print("Ins",Ins)
print("Ops",Ops)


In [[[ 0.003108 -0.001293 -0.014313  0.066973 -0.005188]
  [ 0.00285  -0.002413 -0.01075   0.076443 -0.002525]
  [ 0.003493 -0.001293 -0.012894  0.081873 -0.001826]
  ...
  [ 0.004102  0.008794  0.007954 -0.015832  0.00292 ]
  [ 0.005136  0.006532  0.011427 -0.005082  0.003003]
  [ 0.006331  0.008423  0.008349 -0.017695  0.002504]]

 [[ 0.00285  -0.002413 -0.01075   0.076443 -0.002525]
  [ 0.003493 -0.001293 -0.012894  0.081873 -0.001826]
  [ 0.002415 -0.003059 -0.009761  0.076151 -0.002256]
  ...
  [ 0.005136  0.006532  0.011427 -0.005082  0.003003]
  [ 0.006331  0.008423  0.008349 -0.017695  0.002504]
  [ 0.005997  0.008902  0.013227 -0.021401  0.002087]]

 [[ 0.003493 -0.001293 -0.012894  0.081873 -0.001826]
  [ 0.002415 -0.003059 -0.009761  0.076151 -0.002256]
  [ 0.002466  0.00101  -0.008865  0.070878 -0.001812]
  ...
  [ 0.006331  0.008423  0.008349 -0.017695  0.002504]
  [ 0.005997  0.008902  0.013227 -0.021401  0.002087]
  [ 0.007151  0.006554  0.014034 -0.023459  0.00757 ]]]
O

In [4]:
Xins,Yops=shuffle(xin,y_op)

In [5]:
def normal(dat):
    mina=np.min(dat,axis=(0,1))
    maxa=np.max(dat,axis=(0,1))
    print("mina.shape",mina.shape)
    print("maxa.shape",maxa.shape)
    mina=mina.reshape(1,1,mina.shape[0])
    maxa=maxa.reshape(1,1,maxa.shape[0])
    Datn=(np.copy(dat)-mina)/(maxa-mina)
    return Datn, mina, maxa
Xin_N, min_m, max_m=normal(Xins)

mina.shape (5,)
maxa.shape (5,)


In [6]:
def split(inp,tar,per):
    m=inp.shape[0]
    train=int((m*per)/100)
    xtrn=inp[0:train,:]
    ytrn=tar[0:train,:]
    xvel=inp[train:,:]
    yvel=tar[train:,:]
    return xtrn,ytrn,xvel,yvel
X_train,Y_train, X_vel, Y_vel = split(Xin_N,Yops,80)
print("X_train.shape",X_train.shape)
print("Y_train.shape",Y_train.shape)
print("X_vel.shape",X_vel.shape)
print("Y_vel.shape",Y_vel.shape)

X_train.shape (129040, 100, 5)
Y_train.shape (129040, 15, 5)
X_vel.shape (32261, 100, 5)
Y_vel.shape (32261, 15, 5)


In [7]:
np.save("X_train.npy",X_train)
np.save("Y_train.npy",Y_train)
np.save("X_vel.npy",X_vel)
np.save("Y_vel.npy",Y_vel)
np.save("min_m.npy",min_m)
np.save("max_m.npy",max_m)


In [12]:
X_train_ML =  X_train.reshape(X_train.shape[0],X_train.shape[1]*X_train.shape[2])
print("X_train_ML.shape:",X_train_ML.shape)
Y_train_ML =  Y_train.reshape(Y_train.shape[0],Y_train.shape[1]*Y_train.shape[2])
print("Y_train_ML.shape:",Y_train_ML.shape)
X_vel_ML =  X_vel.reshape(X_vel.shape[0],X_vel.shape[1]*X_vel.shape[2])
print("X_vel_ML.shape:",X_vel_ML.shape)
Y_vel_ML =  Y_vel.reshape(Y_vel.shape[0],Y_vel.shape[1]*Y_vel.shape[2])
print("Y_vel_ML.shape:",Y_vel_ML.shape)

min_m_ML=min_m.reshape(1,min_m.shape[2])
print("min_m_ML.shape:",min_m_ML.shape)
max_m_ML=max_m.reshape(1,max_m.shape[2])
np.save("X_train_ML.npy",X_train_ML)
np.save("Y_train_ML.npy",Y_train_ML)
np.save("X_vel_ML.npy",X_vel)
np.save("Y_vel_ML.npy",Y_vel)
np.save("min_m_ML.npy",min_m)
np.save("max_m_ML.npy",max_m)


X_train_ML.shape: (129040, 500)
Y_train_ML.shape: (129040, 75)
X_vel_ML.shape: (32261, 500)
Y_vel_ML.shape: (32261, 75)
min_m_ML.shape: (1, 5)
