In [1]:
import os
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
os.chdir(r"C:\Users\Aniket\Desktop\INTENTION")
x_train=np.load('X_train_ML.npy')
y_train=np.load('Y_train_ML.npy')
x_vel=np.load("X_vel_ML.npy")
y_vel=np.load("Y_vel_ML.npy")
min_m=np.load("min_m_ML.npy")
max_m=np.load("max_m_ML.npy")

In [2]:
shape=x_train.shape
print("input shape:",shape)
Shapey=y_train.shape
print("output shape:",y_train.shape)
print("x_vel.shape",x_vel.shape)
print("y_vel.shape",y_vel.shape)
print("min_m.shape",min_m.shape)
print("max_m.shape",max_m.shape)
print("x_vel.shape",x_vel.shape)
x_val_reshaped = x_vel.reshape(-1, 500)
print("x_val_reshaped.shspe:",x_val_reshaped.shape)
y_val_reshaped=y_vel.reshape(-1,75)
print("y_val_reshaped.shspe:",y_val_reshaped.shape)

input shape: (129040, 500)
output shape: (129040, 75)
x_vel.shape (32261, 100, 5)
y_vel.shape (32261, 15, 5)
min_m.shape (1, 1, 5)
max_m.shape (1, 1, 5)
x_vel.shape (32261, 100, 5)
x_val_reshaped.shspe: (32261, 500)
y_val_reshaped.shspe: (32261, 75)


In [3]:
import numpy as np
from sklearn.neighbors import KNeighborsRegressor
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import mean_squared_error

scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(x_train)


X_train_split, X_test_split, y_train_split, y_test_split = train_test_split(X_train_scaled, y_train, test_size=0.2, random_state=42)

k_neighbors = 5
knn_regressor = KNeighborsRegressor(n_neighbors=k_neighbors)
knn_regressor.fit(X_train_split, y_train_split)


y_pred = knn_regressor.predict(X_test_split)
mse = mean_squared_error(y_test_split, y_pred)
print("Mean Squared Error:", mse)


Mean Squared Error: 0.7911697573411741


In [17]:
import numpy as np
from sklearn.neighbors import KNeighborsRegressor
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import mean_squared_error, mean_absolute_error, r2_score
scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(x_train)
X_train_split, X_test_split, y_train_split, y_test_split = train_test_split(X_train_scaled, y_train, test_size=0.2, random_state=42)
k_neighbors = 5
knn_regressor = KNeighborsRegressor(n_neighbors=k_neighbors)
knn_regressor.fit(X_train_split, y_train_split)
y_pred = knn_regressor.predict(X_test_split)
mse = mean_squared_error(y_test_split, y_pred)
mae = mean_absolute_error(y_test_split, y_pred)
r2 = r2_score(y_test_split, y_pred)
print("Mean Squared Error:", mse)
print("Mean Absolute Error:", mae)
print("R-squared:", r2)


Mean Squared Error: 0.7911697573411741
Mean Absolute Error: 0.4055531490620996
R-squared: 0.8501075525664487


In [5]:
import numpy as np
from sklearn.neighbors import KNeighborsRegressor
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import mean_squared_error, mean_absolute_error, r2_score

# Assuming you already have X_train and y_train data loaded or defined

scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(x_train)

# Splitting the data (not necessary if already done previously)
X_train_split, X_test_split, y_train_split, y_test_split = train_test_split(X_train_scaled, y_train, test_size=0.2, random_state=42)

k_neighbors = 5
knn_regressor = KNeighborsRegressor(n_neighbors=k_neighbors)
knn_regressor.fit(X_train_split, y_train_split)

# Predictions on the train dataset
y_train_pred = knn_regressor.predict(X_train_split)

# Calculating metrics for the train dataset
train_mse = mean_squared_error(y_train_split, y_train_pred)
train_mae = mean_absolute_error(y_train_split, y_train_pred)
train_r2 = r2_score(y_train_split, y_train_pred)

print("Train Mean Squared Error:", train_mse)
print("Train Mean Absolute Error:", train_mae)
print("Train R-squared:", train_r2)


Train Mean Squared Error: 0.4644591454895479
Train Mean Absolute Error: 0.2988845656674678
Train R-squared: 0.9127889277866427


In [9]:
import numpy as np
from sklearn.neighbors import KNeighborsRegressor
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import mean_absolute_error, r2_score,mean_squared_error

# Assuming you already have X_train, X_val, y_train, and y_val data loaded or defined

scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(x_train)
X_val_scaled = scaler.transform(x_val_reshaped)

# Assuming you already have X_train and y_train data loaded or defined
X_train_split, X_test_split, y_train_split, y_test_split = train_test_split(X_train_scaled, y_train, test_size=0.2, random_state=42)

k_neighbors = 5
knn_regressor = KNeighborsRegressor(n_neighbors=k_neighbors)
knn_regressor.fit(X_train_split, y_train_split)

# Predictions on the validation dataset
y_val_pred = knn_regressor.predict(X_val_scaled)

# Calculating metrics for the validation dataset
val_mae = mean_absolute_error(y_val_reshaped, y_val_pred)
val_r2 = r2_score(y_val_reshaped, y_val_pred)
val_mse=mean_squared_error(y_val_reshaped, y_val_pred)

print("Validation Mean Absolute Error:", val_mae)
print("Validation R-squared:", val_r2)
print("validation mse",val_mse)


Validation Mean Absolute Error: 0.4086380508236362
Validation R-squared: 0.8488559040498868
validation mse 0.805403707136332


In [12]:

y_pred_std = np.std(y_pred)
print("Standard Deviation of Predicted Values:", y_pred_std)


Mean Squared Error: 0.7911697573411741
Mean Absolute Error: 0.4055531490620996
R-squared: 0.8501075525664487
Standard Deviation of Predicted Values: 2.2451714895319874


In [4]:
import psutil

def get_memory_usage():
    process = psutil.Process()
    memory_usage = process.memory_info().rss / (1024.0 ** 2)  # Memory usage in megabytes
    return memory_usage

# Your main code goes here

# Calculate memory usage after executing your main code
memory_used = get_memory_usage()
print("Memory Used (MB):", memory_used)


Memory Used (MB): 1959.87109375


In [5]:
import numpy as np
from sklearn.neighbors import KNeighborsRegressor
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import mean_squared_error
import time

scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(x_train)


X_train_split, X_test_split, y_train_split, y_test_split = train_test_split(X_train_scaled, y_train, test_size=0.2, random_state=42)


k_neighbors = 5
knn_regressor = KNeighborsRegressor(n_neighbors=k_neighbors)


start_time = time.time()


knn_regressor.fit(X_train_split, y_train_split)


end_time = time.time()


y_pred = knn_regressor.predict(X_test_split)
mse = mean_squared_error(y_test_split, y_pred)
training_time = end_time - start_time
print("Mean Squared Error:", mse)
print("Training Time (seconds):", training_time)


Mean Squared Error: 0.7911697573411741
Training Time (seconds): 0.08776593208312988


In [4]:
print("shape of min_m:",min_m.shape)
min_m_reshape=min_m.reshape(-1,5)
print("min_m_reshape=",min_m_reshape.shape)
max_m_reshape=max_m.reshape(-1,5)
print("max_m_reshape=",max_m_reshape.shape)

shape of min_m: (1, 1, 5)
min_m_reshape= (1, 5)
max_m_reshape= (1, 5)


In [5]:
x_test12=np.load('x_in12.npy')
y_test12=np.load('y_op12.npy')
print("x_test12.shape:",x_test12.shape)
print("y_test12.shape:",y_test12.shape)


x_test12.shape: (16046, 100, 5)
y_test12.shape: (16046, 15, 5)


In [13]:
x_norm=(x_vel-min_m_reshape)/(max_m_reshape-min_m_reshape)
print(x_norm)

[[[0.38765795 0.58969688 0.42375179 0.48870756 0.46259281]
  [0.38739463 0.59237653 0.42410159 0.48742557 0.46261372]
  [0.3871609  0.59539077 0.4243439  0.48479041 0.46257292]
  ...
  [0.38790225 0.56091452 0.42446442 0.48192887 0.46226199]
  [0.38789715 0.56205711 0.42421482 0.48784657 0.4622558 ]
  [0.38796273 0.56361785 0.4239423  0.49314905 0.46224572]]

 [[0.38766183 0.56741378 0.42493358 0.48181887 0.46152602]
  [0.38781015 0.5673909  0.42485809 0.48201816 0.46161478]
  [0.38788976 0.56734707 0.42478618 0.48181225 0.46176757]
  ...
  [0.38708791 0.56916995 0.42448228 0.48934221 0.46178264]
  [0.38709125 0.56916124 0.42445797 0.48931752 0.46178138]
  [0.38710129 0.56924601 0.42442869 0.48934716 0.46178796]]

 [[0.38790454 0.55294813 0.42468149 0.47845723 0.46259024]
  [0.388121   0.5503684  0.4247146  0.4782455  0.46245642]
  [0.38831065 0.5496891  0.4247228  0.47821978 0.46248794]
  ...
  [0.38757281 0.5577934  0.42431298 0.48356047 0.462911  ]
  [0.38797315 0.56277446 0.4241534

In [14]:
x_test12_reshape= x_test12.reshape(-1, 500)
print("x_test12_reshape shape:",x_test12_reshape.shape)
y_test12_reshape= y_test12.reshape(-1, 75)
print("y_test12_reshape shape:",y_test12_reshape.shape)

x_test12_reshape shape: (16046, 500)
y_test12_reshape shape: (16046, 75)


In [20]:
y_pred_test = knn_regressor.predict(x_val_reshaped)

In [23]:
print(x_norm)

x_test12_reshape = x_test12.reshape(-1, 500)
print("x_test12_reshape shape:", x_test12_reshape.shape)

y_test12_reshape = y_test12.reshape(-1, 75)
print("y_test12_reshape shape:", y_test12_reshape.shape)

# Make predictions using the model and x_test12_reshape
y_pred_test = knn_regressor.predict(x_test12_reshape)

# Perform evaluation with consistent number of samples
from sklearn.metrics import r2_score
from sklearn.metrics import mean_squared_error
from sklearn.metrics import mean_absolute_error

print(mean_squared_error(y_test12_reshape, y_pred_test))
print(r2_score(y_test12_reshape, y_pred_test))
print(mean_absolute_error(y_test12_reshape, y_pred_test))

[[[0.38765795 0.58969688 0.42375179 0.48870756 0.46259281]
  [0.38739463 0.59237653 0.42410159 0.48742557 0.46261372]
  [0.3871609  0.59539077 0.4243439  0.48479041 0.46257292]
  ...
  [0.38790225 0.56091452 0.42446442 0.48192887 0.46226199]
  [0.38789715 0.56205711 0.42421482 0.48784657 0.4622558 ]
  [0.38796273 0.56361785 0.4239423  0.49314905 0.46224572]]

 [[0.38766183 0.56741378 0.42493358 0.48181887 0.46152602]
  [0.38781015 0.5673909  0.42485809 0.48201816 0.46161478]
  [0.38788976 0.56734707 0.42478618 0.48181225 0.46176757]
  ...
  [0.38708791 0.56916995 0.42448228 0.48934221 0.46178264]
  [0.38709125 0.56916124 0.42445797 0.48931752 0.46178138]
  [0.38710129 0.56924601 0.42442869 0.48934716 0.46178796]]

 [[0.38790454 0.55294813 0.42468149 0.47845723 0.46259024]
  [0.388121   0.5503684  0.4247146  0.4782455  0.46245642]
  [0.38831065 0.5496891  0.4247228  0.47821978 0.46248794]
  ...
  [0.38757281 0.5577934  0.42431298 0.48356047 0.462911  ]
  [0.38797315 0.56277446 0.4241534

In [20]:
import numpy as np

y_pred = knn_regressor.predict(x_test12_reshape)


std_deviation = np.std(y_pred_test)

print("Standard Deviation of Predictions:", std_deviation)

Standard Deviation of Predictions: 2.9542939472165886


In [ ]:
import numpy as np
import matplotlib.pyplot as plt
import tensorflow as tf
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import mean_squared_error

# Assuming you have already defined x_train and y_train

# Standardize the data
scaler = StandardScaler()
x_train_scaled = scaler.fit_transform(x_train)

# Train-test split
x_train_split, x_val, y_train_split, y_val = train_test_split(x_train_scaled, y_train, test_size=0.2, random_state=42)

# Create the K-nearest neighbors regressor model
k_neighbors = 5
knn_regressor = KNeighborsRegressor(n_neighbors=k_neighbors)

# Train the model and monitor training and validation loss
epochs = 50
train_loss_history = []
val_loss_history = []

for epoch in range(epochs):
    # Fit the model to the training data for each epoch
    knn_regressor.fit(x_train_split, y_train_split)

    # Predict on training and validation data
    y_pred_train = knn_regressor.predict(x_train_split)
    y_pred_val = knn_regressor.predict(x_val)

    # Calculate mean squared error for training and validation data
    train_loss = mean_squared_error(y_train_split, y_pred_train)
    val_loss = mean_squared_error(y_val, y_pred_val)

    train_loss_history.append(train_loss)
    val_loss_history.append(val_loss)

# Plot the training and validation loss curves
plt.figure(figsize=(8, 6))
plt.plot(range(1, epochs + 1), train_loss_history, label='Training Loss')
plt.plot(range(1, epochs + 1), val_loss_history, label='Validation Loss')
plt.xlabel('Epochs')
plt.ylabel('Mean Squared Error')
plt.title('Training and Validation Loss Curves')
plt.legend()
plt.grid(True)
plt.show()
