In [1]:
import os
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [2]:
cd=os.getcwd()
print(cd)


C:\Users\Aniket


In [3]:
os.chdir(r"C:\Users\Aniket\Desktop\INTENTION")

In [4]:
cd=os.getcwd()
print(cd)

C:\Users\Aniket\Desktop\INTENTION


In [5]:
items=os.listdir(cd)
print(items)

['arrays.npz', 'U001_test_intention.csv', 'U001_train_intention.csv', 'U001_val_intention.csv', 'U002_test_intention.csv', 'U002_train_intention.csv', 'U002_val_intention.csv', 'U003_test_intention.csv', 'U003_train_intention.csv', 'U003_val_intention.csv', 'U004_test_intention.csv', 'U004_train_intention.csv', 'U004_val_intention.csv', 'U005_test_intention.csv', 'U005_train_intention.csv', 'U005_val_intention.csv', 'U006_test_intention.csv', 'U006_train_intention.csv', 'U006_val_intention.csv', 'U007_test_intention.csv', 'U007_train_intention.csv', 'U007_val_intention.csv', 'U008_test_intention.csv', 'U008_train_intention.csv', 'U008_val_intention.csv', 'U009_test_intention.csv', 'U009_train_intention.csv', 'U009_val_intention.csv', 'U010_test_intention.csv', 'U010_train_intention.csv', 'U010_val_intention.csv', 'U011_test_intention.csv', 'U011_train_intention.csv', 'U011_val_intention.csv', 'U012_test_intention.csv', 'U012_train_intention.csv', 'U012_val_intention.csv', 'x_in=.npy']


In [6]:
path=os.path.join(cd,"U001_train_intention.csv")
df1=pd.read_csv(path)
print(df1.head(5))

   Gyro_X_C9  Gyro_Y_C9  Gyro_Z_C9  Gyro_X_3B  Gyro_Y_3B  Gyro_Z_3B  \
0   0.012343   0.011154   0.046459   0.280846   0.135446   0.161358   
1   0.055380  -0.006489   0.026373   0.243645   0.122282   0.157132   
2   0.122433  -0.021939   0.019428   0.232980   0.125588   0.150065   
3   0.202340  -0.025395   0.003973   0.247104   0.105518   0.143457   
4   0.268421  -0.013397   0.001976   0.219017   0.100808   0.150137   

   Gyro_X_B5  Gyro_Y_B5  Gyro_Z_B5  Gyro_X_B6  Gyro_Y_B6  Gyro_Z_B6  \
0   0.070465  -0.057262   0.084950  -0.073917  -0.320395  -0.011203   
1   0.054317  -0.071056   0.086333  -0.065672  -0.322257  -0.009219   
2   0.036555  -0.085724   0.091059  -0.053523  -0.315645  -0.012640   
3   0.022009  -0.100458   0.094337  -0.060104  -0.311796  -0.013642   
4   0.009582  -0.107500   0.108382  -0.077943  -0.306367  -0.016528   

   Gyro_X_BB  Gyro_Y_BB  Gyro_Z_BB  target  
0  -0.223229  -0.028756  -0.044222       0  
1  -0.225826  -0.033528  -0.042486       0  
2  -0.23178

In [7]:
print(df1.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 109875 entries, 0 to 109874
Data columns (total 16 columns):
 #   Column     Non-Null Count   Dtype  
---  ------     --------------   -----  
 0   Gyro_X_C9  109875 non-null  float64
 1   Gyro_Y_C9  109875 non-null  float64
 2   Gyro_Z_C9  109875 non-null  float64
 3   Gyro_X_3B  109875 non-null  float64
 4   Gyro_Y_3B  109875 non-null  float64
 5   Gyro_Z_3B  109875 non-null  float64
 6   Gyro_X_B5  109875 non-null  float64
 7   Gyro_Y_B5  109875 non-null  float64
 8   Gyro_Z_B5  109875 non-null  float64
 9   Gyro_X_B6  109875 non-null  float64
 10  Gyro_Y_B6  109875 non-null  float64
 11  Gyro_Z_B6  109875 non-null  float64
 12  Gyro_X_BB  109875 non-null  float64
 13  Gyro_Y_BB  109875 non-null  float64
 14  Gyro_Z_BB  109875 non-null  float64
 15  target     109875 non-null  int64  
dtypes: float64(15), int64(1)
memory usage: 13.4 MB
None


In [8]:
Gyro_Y=df1.iloc[:,[1,4,7,10,13]]
Dat=Gyro_Y.values
print(Gyro_Y.head())
print(Dat.shape)
print(Dat)

   Gyro_Y_C9  Gyro_Y_3B  Gyro_Y_B5  Gyro_Y_B6  Gyro_Y_BB
0   0.011154   0.135446  -0.057262  -0.320395  -0.028756
1  -0.006489   0.122282  -0.071056  -0.322257  -0.033528
2  -0.021939   0.125588  -0.085724  -0.315645  -0.035868
3  -0.025395   0.105518  -0.100458  -0.311796  -0.048283
4  -0.013397   0.100808  -0.107500  -0.306367  -0.053789
(109875, 5)
[[ 0.011154  0.135446 -0.057262 -0.320395 -0.028756]
 [-0.006489  0.122282 -0.071056 -0.322257 -0.033528]
 [-0.021939  0.125588 -0.085724 -0.315645 -0.035868]
 ...
 [ 0.011339  0.000608  0.015854 -0.008076 -0.007098]
 [ 0.011692  0.002705  0.015118 -0.005818 -0.003477]
 [ 0.012394  0.000972  0.012809 -0.006303 -0.00377 ]]


In [9]:
#windowed output shape [m x o] where m=Sample-(window+output)+1
#and windowed input shape will be [mxw].

Sample=Gyro_Y.shape[0]
print(Sample)
window=100
output=15
m=Sample-(window+output)+1

X=np.zeros((m,window))
y=np.zeros((m,output))
print(m)

109875
109761


In [14]:
import numpy as np



#taking window input as 100 and window ouput as 15 for sample=m  
x_in = np.zeros((m,100,5))
y_op = np.zeros((m,15,5))


for i in range(m):
    # Store the first 100 rows
   # print("x_in[i:,:,].shape",x_in[i,:,:].shape,"y_op[i:,:,].shape",y_op[i,:,:].shape,"Dat[i:i+100,:].shape",Dat[i:i+100,:].shape,"Dat[i+100:i+115,:].shape",Dat[i+100:i+115,:].shape)
    x_in[i,:,:] =Dat[i:i+100,:]
    y_op[i,:,:]=Dat[i+100:i+115,:]
     
    
 
    

    # Print the stored arrays
print("x_in:")
print(x_in.shape)
print(y_op.shape)
   

    

 




x_in:
(109761, 100, 5)
(109761, 15, 5)


In [15]:


# Save arrays to a file
np.save('x_in.npy',x_in)
np.save('y_op.npy',y_op)
