In [14]:
import os
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [15]:
cd=os.getcwd()
print(cd)


C:\Users\Aniket\Desktop\INTENTION


In [16]:
os.chdir(r"C:\Users\Aniket\Desktop\INTENTION")

In [17]:
cd=os.getcwd()
print(cd)

C:\Users\Aniket\Desktop\INTENTION


In [18]:
items=os.listdir(cd)
print(items)

['arrays.npz', 'max_m.npy', 'max_m_ML.npy', 'min_m.npy', 'min_m_ML.npy', 'U001_test_intention.csv', 'U001_train_intention.csv', 'U001_val_intention.csv', 'U002_test_intention.csv', 'U002_train_intention.csv', 'U002_val_intention.csv', 'U003_test_intention.csv', 'U003_train_intention.csv', 'U003_val_intention.csv', 'U004_test_intention.csv', 'U004_train_intention.csv', 'U004_val_intention.csv', 'U005_test_intention.csv', 'U005_train_intention.csv', 'U005_val_intention.csv', 'U006_test_intention.csv', 'U006_train_intention.csv', 'U006_val_intention.csv', 'U007_test_intention.csv', 'U007_train_intention.csv', 'U007_val_intention.csv', 'U008_test_intention.csv', 'U008_train_intention.csv', 'U008_val_intention.csv', 'U009_test_intention.csv', 'U009_train_intention.csv', 'U009_val_intention.csv', 'U010_test_intention.csv', 'U010_train_intention.csv', 'U010_val_intention.csv', 'U011_test_intention.csv', 'U011_train_intention.csv', 'U011_val_intention.csv', 'U012_test_intention.csv', 'U012_tra

In [19]:
path=os.path.join(cd,"U002_test_intention.csv")
df1=pd.read_csv(path)
print(df1.head(5))

   Axel_X_C9  Axel_Y_C9  Axel_Z_C9  Gyro_X_C9  Gyro_Y_C9  Gyro_Z_C9  \
0   9.843251   0.334928  -0.830445   0.002227  -0.005310   0.005479   
1   9.864525   0.390093  -0.834568  -0.003177  -0.009675   0.006931   
2   9.857777   0.367857  -0.878942  -0.002954  -0.011297   0.009508   
3   9.806334   0.353794  -0.893461  -0.008732  -0.019567   0.008551   
4   9.805834   0.320327  -0.906801  -0.014015  -0.022630   0.010806   

   Axel_X_3B  Axel_Y_3B  Axel_Z_3B  Gyro_X_3B  ...  Gyro_X_B6  Gyro_Y_B6  \
0   9.690310   0.846790  -1.386316   0.022893  ...   0.020320   0.010041   
1   9.686135   0.858660  -1.419828   0.024733  ...  -0.015275   0.017349   
2   9.666782   0.813488  -1.397846   0.023077  ...  -0.024598   0.012132   
3   9.711036   0.828425  -1.436571   0.017842  ...   0.017524  -0.018013   
4   9.689048   0.805189  -1.425609   0.008556  ...   0.036743  -0.063033   

   Gyro_Z_B6  Axel_X_BB  Axel_Y_BB  Axel_Z_BB  Gyro_X_BB  Gyro_Y_BB  \
0  -0.016352   9.445992  -2.216411   2.190420

In [20]:
print(df1.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 15801 entries, 0 to 15800
Data columns (total 31 columns):
 #   Column     Non-Null Count  Dtype  
---  ------     --------------  -----  
 0   Axel_X_C9  15801 non-null  float64
 1   Axel_Y_C9  15801 non-null  float64
 2   Axel_Z_C9  15801 non-null  float64
 3   Gyro_X_C9  15801 non-null  float64
 4   Gyro_Y_C9  15801 non-null  float64
 5   Gyro_Z_C9  15801 non-null  float64
 6   Axel_X_3B  15801 non-null  float64
 7   Axel_Y_3B  15801 non-null  float64
 8   Axel_Z_3B  15801 non-null  float64
 9   Gyro_X_3B  15801 non-null  float64
 10  Gyro_Y_3B  15801 non-null  float64
 11  Gyro_Z_3B  15801 non-null  float64
 12  Axel_X_B5  15801 non-null  float64
 13  Axel_Y_B5  15801 non-null  float64
 14  Axel_Z_B5  15801 non-null  float64
 15  Gyro_X_B5  15801 non-null  float64
 16  Gyro_Y_B5  15801 non-null  float64
 17  Gyro_Z_B5  15801 non-null  float64
 18  Axel_X_B6  15801 non-null  float64
 19  Axel_Y_B6  15801 non-null  float64
 20  Axel_Z

In [21]:
Gyro_Y=df1.iloc[:,[1,4,7,10,13]]
Dat=Gyro_Y.values
print(Gyro_Y.head())
print(Dat.shape)
print(Dat)

   Axel_Y_C9  Gyro_Y_C9  Axel_Y_3B  Gyro_Y_3B  Axel_Y_B5
0   0.334928  -0.005310   0.846790  -0.008737   0.065735
1   0.390093  -0.009675   0.858660  -0.010782   0.076383
2   0.367857  -0.011297   0.813488  -0.010361   0.082136
3   0.353794  -0.019567   0.828425  -0.018976   0.115326
4   0.320327  -0.022630   0.805189  -0.016854   0.120884
(15801, 5)
[[ 0.334928 -0.00531   0.84679  -0.008737  0.065735]
 [ 0.390093 -0.009675  0.85866  -0.010782  0.076383]
 [ 0.367857 -0.011297  0.813488 -0.010361  0.082136]
 ...
 [ 0.93323  -0.69669   3.47064   0.682885  0.410624]
 [ 0.995119 -0.662013  0.964177  0.761033  0.292278]
 [ 1.208262 -0.635054 -1.689214  0.534524 -0.01193 ]]


In [22]:
#windowed output shape [m x o] where m=Sample-(window+output)+1
#and windowed input shape will be [mxw].

Sample=Gyro_Y.shape[0]
print(Sample)
window=100
output=15
m=Sample-(window+output)+1

X=np.zeros((m,window))
y=np.zeros((m,output))
print(m)

15801
15687


In [23]:
import numpy as np



#taking window input as 100 and window ouput as 15 for sample=m  
x_in = np.zeros((m,100,5))
y_op = np.zeros((m,15,5))


for i in range(m):
    # Store the first 100 rows
   # print("x_in[i:,:,].shape",x_in[i,:,:].shape,"y_op[i:,:,].shape",y_op[i,:,:].shape,"Dat[i:i+100,:].shape",Dat[i:i+100,:].shape,"Dat[i+100:i+115,:].shape",Dat[i+100:i+115,:].shape)
    x_in[i,:,:] =Dat[i:i+100,:]
    y_op[i,:,:]=Dat[i+100:i+115,:]
     
    
 
    

    # Print the stored arrays
print("x_in:")
print(x_in.shape)
print(y_op.shape)
   

    

 




x_in:
(15687, 100, 5)
(15687, 15, 5)


In [24]:


# Save arrays to a file
np.save('x_in2.npy',x_in)
np.save('y_op2.npy',y_op)
