In [16]:
import os
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [17]:
cd=os.getcwd()
print(cd)


C:\Users\Aniket\Desktop\INTENTION


In [18]:
os.chdir(r"C:\Users\Aniket\Desktop\INTENTION")

In [19]:
cd=os.getcwd()
print(cd)

C:\Users\Aniket\Desktop\INTENTION


In [20]:
items=os.listdir(cd)
print(items)

['arrays.npz', 'U001_test_intention.csv', 'U001_train_intention.csv', 'U001_val_intention.csv', 'U002_test_intention.csv', 'U002_train_intention.csv', 'U002_val_intention.csv', 'U003_test_intention.csv', 'U003_train_intention.csv', 'U003_val_intention.csv', 'U004_test_intention.csv', 'U004_train_intention.csv', 'U004_val_intention.csv', 'U005_test_intention.csv', 'U005_train_intention.csv', 'U005_val_intention.csv', 'U006_test_intention.csv', 'U006_train_intention.csv', 'U006_val_intention.csv', 'U007_test_intention.csv', 'U007_train_intention.csv', 'U007_val_intention.csv', 'U008_test_intention.csv', 'U008_train_intention.csv', 'U008_val_intention.csv', 'U009_test_intention.csv', 'U009_train_intention.csv', 'U009_val_intention.csv', 'U010_test_intention.csv', 'U010_train_intention.csv', 'U010_val_intention.csv', 'U011_test_intention.csv', 'U011_train_intention.csv', 'U011_val_intention.csv', 'U012_test_intention.csv', 'U012_train_intention.csv', 'U012_val_intention.csv', 'x_in.npy', '

In [21]:
path=os.path.join(cd,"U002_train_intention.csv")
df1=pd.read_csv(path)
print(df1.head(5))

   Axel_X_C9  Axel_Y_C9  Axel_Z_C9  Gyro_X_C9  Gyro_Y_C9  Gyro_Z_C9  \
0   8.199182   2.207052   0.783509   0.850685  -1.072093   0.410495   
1   8.438137   2.519922   1.953930   0.683856  -1.214931   0.386091   
2   9.311604   3.379221   2.639236   0.523188  -1.256644   0.402437   
3  10.366902   4.325544   2.550942   0.539613  -1.177270   0.409964   
4  10.927887   4.712421   1.597345   0.666779  -0.994159   0.425805   

   Axel_X_3B  Axel_Y_3B  Axel_Z_3B  Gyro_X_3B  ...  Gyro_X_B6  Gyro_Y_B6  \
0   4.723330   2.392470   2.848952  -0.961156  ...   0.210884  -0.007829   
1   6.291862   1.844391   4.989606  -1.412136  ...   0.179963   0.051064   
2   9.119535   1.955539   9.633720  -1.726296  ...   0.142519   0.121885   
3  13.120243   2.172550  15.220164  -1.591408  ...   0.071071   0.178092   
4  18.622875   2.935114  15.993565  -0.616234  ...  -0.015241   0.211938   

   Gyro_Z_B6  Axel_X_BB  Axel_Y_BB  Axel_Z_BB  Gyro_X_BB  Gyro_Y_BB  \
0   0.120377   9.644582  -4.491251   2.020048

In [22]:
print(df1.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 89366 entries, 0 to 89365
Data columns (total 31 columns):
 #   Column     Non-Null Count  Dtype  
---  ------     --------------  -----  
 0   Axel_X_C9  89366 non-null  float64
 1   Axel_Y_C9  89366 non-null  float64
 2   Axel_Z_C9  89366 non-null  float64
 3   Gyro_X_C9  89366 non-null  float64
 4   Gyro_Y_C9  89366 non-null  float64
 5   Gyro_Z_C9  89366 non-null  float64
 6   Axel_X_3B  89366 non-null  float64
 7   Axel_Y_3B  89366 non-null  float64
 8   Axel_Z_3B  89366 non-null  float64
 9   Gyro_X_3B  89366 non-null  float64
 10  Gyro_Y_3B  89366 non-null  float64
 11  Gyro_Z_3B  89366 non-null  float64
 12  Axel_X_B5  89366 non-null  float64
 13  Axel_Y_B5  89366 non-null  float64
 14  Axel_Z_B5  89366 non-null  float64
 15  Gyro_X_B5  89366 non-null  float64
 16  Gyro_Y_B5  89366 non-null  float64
 17  Gyro_Z_B5  89366 non-null  float64
 18  Axel_X_B6  89366 non-null  float64
 19  Axel_Y_B6  89366 non-null  float64
 20  Axel_Z

In [23]:
Gyro_Y=df1.iloc[:,[1,4,7,10,13]]
Dat=Gyro_Y.values
print(Gyro_Y.head())
print(Dat.shape)
print(Dat)

   Axel_Y_C9  Gyro_Y_C9  Axel_Y_3B  Gyro_Y_3B  Axel_Y_B5
0   2.207052  -1.072093   2.392470  -2.360089   0.697528
1   2.519922  -1.214931   1.844391  -2.937608   0.555808
2   3.379221  -1.256644   1.955539  -3.256176   0.476037
3   4.325544  -1.177270   2.172550  -3.140566   0.353550
4   4.712421  -0.994159   2.935114  -2.785944   0.266792
(89366, 5)
[[ 2.207052e+00 -1.072093e+00  2.392470e+00 -2.360089e+00  6.975280e-01]
 [ 2.519922e+00 -1.214931e+00  1.844391e+00 -2.937608e+00  5.558080e-01]
 [ 3.379221e+00 -1.256644e+00  1.955539e+00 -3.256176e+00  4.760370e-01]
 ...
 [ 5.794500e-02  4.756000e-03  9.639630e-01 -6.417000e-03  7.631360e-01]
 [ 9.070700e-02  1.228000e-03  9.575970e-01 -5.347000e-03  7.666820e-01]
 [ 6.113300e-02 -2.625000e-03  9.643810e-01 -5.654000e-03  7.975600e-01]]


In [24]:
#windowed output shape [m x o] where m=Sample-(window+output)+1
#and windowed input shape will be [mxw].

Sample=Gyro_Y.shape[0]
print(Sample)
window=100
output=15
m=Sample-(window+output)+1

X=np.zeros((m,window))
y=np.zeros((m,output))
print(m)

89366
89252


In [25]:
import numpy as np



#taking window input as 100 and window ouput as 15 for sample=m  
x_in = np.zeros((m,100,5))
y_op = np.zeros((m,15,5))


for i in range(m):
    # Store the first 100 rows
   # print("x_in[i:,:,].shape",x_in[i,:,:].shape,"y_op[i:,:,].shape",y_op[i,:,:].shape,"Dat[i:i+100,:].shape",Dat[i:i+100,:].shape,"Dat[i+100:i+115,:].shape",Dat[i+100:i+115,:].shape)
    x_in[i,:,:] =Dat[i:i+100,:]
    y_op[i,:,:]=Dat[i+100:i+115,:]
     
    
 
    

    # Print the stored arrays
print("x_in:")
print(x_in.shape)
print(y_op.shape)
   

    

 




x_in:
(89252, 100, 5)
(89252, 15, 5)


In [26]:


# Save arrays to a file
np.save('x_in2.npy',x_in)
np.save('y_op2.npy',y_op)
