In [25]:
import os
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [26]:
cd=os.getcwd()
print(cd)


C:\Users\Aniket\Desktop\INTENTION


In [27]:
os.chdir(r"C:\Users\Aniket\Desktop\INTENTION")

In [28]:
cd=os.getcwd()
print(cd)

C:\Users\Aniket\Desktop\INTENTION


In [29]:
items=os.listdir(cd)
print(items)

['arrays.npz', 'max_m.npy', 'max_m_ML.npy', 'min_m.npy', 'min_m_ML.npy', 'U001_test_intention.csv', 'U001_train_intention.csv', 'U001_val_intention.csv', 'U002_test_intention.csv', 'U002_train_intention.csv', 'U002_val_intention.csv', 'U003_test_intention.csv', 'U003_train_intention.csv', 'U003_val_intention.csv', 'U004_test_intention.csv', 'U004_train_intention.csv', 'U004_val_intention.csv', 'U005_test_intention.csv', 'U005_train_intention.csv', 'U005_val_intention.csv', 'U006_test_intention.csv', 'U006_train_intention.csv', 'U006_val_intention.csv', 'U007_test_intention.csv', 'U007_train_intention.csv', 'U007_val_intention.csv', 'U008_test_intention.csv', 'U008_train_intention.csv', 'U008_val_intention.csv', 'U009_test_intention.csv', 'U009_train_intention.csv', 'U009_val_intention.csv', 'U010_test_intention.csv', 'U010_train_intention.csv', 'U010_val_intention.csv', 'U011_test_intention.csv', 'U011_train_intention.csv', 'U011_val_intention.csv', 'U012_test_intention.csv', 'U012_tra

In [30]:
path=os.path.join(cd,"U003_test_intention.csv")
df1=pd.read_csv(path)
print(df1.head(5))

   Axel_X_C9  Axel_Y_C9  Axel_Z_C9  Gyro_X_C9  Gyro_Y_C9  Gyro_Z_C9  \
0   9.429842  -1.609110  -2.613189  -0.028909   0.014299   0.011753   
1   9.381990  -1.607649  -2.638288  -0.028938   0.012773   0.011754   
2   9.405759  -1.608808  -2.612468  -0.028943   0.011246   0.010229   
3   9.355571  -1.607153  -2.564651  -0.027471   0.009692   0.011779   
4   9.382309  -1.608499  -2.636637  -0.018277   0.007987   0.007344   

   Axel_X_3B  Axel_Y_3B  Axel_Z_3B  Gyro_X_3B  ...  Gyro_X_B6  Gyro_Y_B6  \
0   9.342097  -0.099275  -3.016465  -0.036542  ...  -0.015071  -0.015652   
1   9.342905  -0.125477  -3.036630  -0.050311  ...  -0.019665  -0.019004   
2   9.316814  -0.220475  -3.003836  -0.065622  ...  -0.016556  -0.020366   
3   9.269161  -0.246441  -3.049972  -0.091558  ...  -0.016589  -0.017258   
4   9.270345  -0.246416  -3.072384  -0.114456  ...  -0.018156  -0.015815   

   Gyro_Z_B6  Axel_X_BB  Axel_Y_BB  Axel_Z_BB  Gyro_X_BB  Gyro_Y_BB  \
0  -0.003823   9.136040  -3.591238   2.027055

In [31]:
print(df1.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 16006 entries, 0 to 16005
Data columns (total 31 columns):
 #   Column     Non-Null Count  Dtype  
---  ------     --------------  -----  
 0   Axel_X_C9  16006 non-null  float64
 1   Axel_Y_C9  16006 non-null  float64
 2   Axel_Z_C9  16006 non-null  float64
 3   Gyro_X_C9  16006 non-null  float64
 4   Gyro_Y_C9  16006 non-null  float64
 5   Gyro_Z_C9  16006 non-null  float64
 6   Axel_X_3B  16006 non-null  float64
 7   Axel_Y_3B  16006 non-null  float64
 8   Axel_Z_3B  16006 non-null  float64
 9   Gyro_X_3B  16006 non-null  float64
 10  Gyro_Y_3B  16006 non-null  float64
 11  Gyro_Z_3B  16006 non-null  float64
 12  Axel_X_B5  16006 non-null  float64
 13  Axel_Y_B5  16006 non-null  float64
 14  Axel_Z_B5  16006 non-null  float64
 15  Gyro_X_B5  16006 non-null  float64
 16  Gyro_Y_B5  16006 non-null  float64
 17  Gyro_Z_B5  16006 non-null  float64
 18  Axel_X_B6  16006 non-null  float64
 19  Axel_Y_B6  16006 non-null  float64
 20  Axel_Z

In [32]:
Gyro_Y=df1.iloc[:,[1,4,7,10,13]]
Dat=Gyro_Y.values
print(Gyro_Y.head())
print(Dat.shape)
print(Dat)

   Axel_Y_C9  Gyro_Y_C9  Axel_Y_3B  Gyro_Y_3B  Axel_Y_B5
0  -1.609110   0.014299  -0.099275   0.028370   3.865306
1  -1.607649   0.012773  -0.125477   0.025442   3.848827
2  -1.608808   0.011246  -0.220475   0.022584   3.829464
3  -1.607153   0.009692  -0.246441   0.022766   3.899702
4  -1.608499   0.007987  -0.246416   0.024554   3.933587
(16006, 5)
[[-1.609110e+00  1.429900e-02 -9.927500e-02  2.837000e-02  3.865306e+00]
 [-1.607649e+00  1.277300e-02 -1.254770e-01  2.544200e-02  3.848827e+00]
 [-1.608808e+00  1.124600e-02 -2.204750e-01  2.258400e-02  3.829464e+00]
 ...
 [-1.104525e+00 -1.836400e-02 -3.991510e-01  3.161000e-03  3.404867e+00]
 [-1.117145e+00 -2.730900e-02 -4.300920e-01  3.699000e-03  3.437840e+00]
 [-1.164998e+00 -1.043700e-02 -4.010380e-01  3.798000e-03  3.397613e+00]]


In [33]:
#windowed output shape [m x o] where m=Sample-(window+output)+1
#and windowed input shape will be [mxw].

Sample=Gyro_Y.shape[0]
print(Sample)
window=100
output=15
m=Sample-(window+output)+1

X=np.zeros((m,window))
y=np.zeros((m,output))
print(m)

16006
15892


In [34]:
import numpy as np



#taking window input as 100 and window ouput as 15 for sample=m  
x_in = np.zeros((m,100,5))
y_op = np.zeros((m,15,5))


for i in range(m):
    # Store the first 100 rows
   # print("x_in[i:,:,].shape",x_in[i,:,:].shape,"y_op[i:,:,].shape",y_op[i,:,:].shape,"Dat[i:i+100,:].shape",Dat[i:i+100,:].shape,"Dat[i+100:i+115,:].shape",Dat[i+100:i+115,:].shape)
    x_in[i,:,:] =Dat[i:i+100,:]
    y_op[i,:,:]=Dat[i+100:i+115,:]
     
    
 
    

    # Print the stored arrays
print("x_in:")
print(x_in.shape)
print(y_op.shape)
   

    

 




x_in:
(15892, 100, 5)
(15892, 15, 5)


In [35]:


# Save arrays to a file
np.save('x_in3.npy',x_in)
np.save('y_op3.npy',y_op)


In [4]:
import os
from zipfile import ZipFile

# Code to be saved
code = """
import os
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
cd=os.getcwd()
print(cd)
os.chdir(r"C:\Users\Aniket\Desktop\INTENTION")
items=os.listdir(cd)
print(items)
path=os.path.join(cd,"U003_test_intention.csv")
df1=pd.read_csv(path)
print(df1.head(5))
print(df1.info())
Gyro_Y=df1.iloc[:,[1,4,7,10,13]]
Dat=Gyro_Y.values
print(Gyro_Y.head())
print(Dat.shape)
print(Dat)




#windowed output shape [m x o] where m=Sample-(window+output)+1
#and windowed input shape will be [mxw].
Sample=Gyro_Y.shape[0]
print(Sample)
window=100
output=15
m=Sample-(window+output)+1
import numpy as np



#taking window input as 100 and window ouput as 15 for sample=m  
x_in = np.zeros((m,100,5))
y_op = np.zeros((m,15,5))


for i in range(m):
    # Store the first 100 rows
   # print("x_in[i:,:,].shape",x_in[i,:,:].shape,"y_op[i:,:,].shape",y_op[i,:,:].shape,"Dat[i:i+100,:].shape",Dat[i:i+100,:].shape,"Dat[i+100:i+115,:].shape",Dat[i+100:i+115,:].shape)
    x_in[i,:,:] =Dat[i:i+100,:]
    y_op[i,:,:]=Dat[i+100:i+115,:]
     
    
 
    

    # Print the stored arrays
print("x_in:")
print(x_in.shape)
print(y_op.shape)
   


X=np.zeros((m,window))
y=np.zeros((m,output))
print(m)

# Save arrays to a file
np.save('x_in3.npy',x_in)
np.save('y_op3.npy',y_op)
"""


zip_filename = "code_archive.zip"

# Create a ZipFile object in write mode
with ZipFile(zip_filename, 'w') as zip:
    # Add the code as a text file to the zip file
    zip.writestr("code.txt", code)

# Print a message indicating that the zip file has been created
print(f"Zip file '{zip_filename}' created successfully.")


SyntaxError: (unicode error) 'unicodeescape' codec can't decode bytes in position 120-121: truncated \UXXXXXXXX escape (1447629700.py, line 68)

In [6]:
import os
from zipfile import ZipFile
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

# Save the current working directory
original_directory = os.getcwd()

# Change the working directory to the desired location
os.chdir(r"C:\Users\Aniket\Desktop\INTENTION")

# Code to load data and process it
cd = os.getcwd()
print(cd)
items = os.listdir(cd)
print(items)
path = os.path.join(cd, "U003_test_intention.csv")
df1 = pd.read_csv(path)
print(df1.head(5))
print(df1.info())
Gyro_Y = df1.iloc[:, [1, 4, 7, 10, 13]]
Dat = Gyro_Y.values
print(Gyro_Y.head())
print(Dat.shape)
print(Dat)

# windowed output shape [m x o] where m=Sample-(window+output)+1
# and windowed input shape will be [mxw].
Sample = Gyro_Y.shape[0]
print(Sample)
window = 100
output = 15
m = Sample - (window + output) + 1
import numpy as np

# taking window input as 100 and window ouput as 15 for sample=m
x_in = np.zeros((m, 100, 5))
y_op = np.zeros((m, 15, 5))

for i in range(m):
    x_in[i, :, :] = Dat[i:i + 100, :]
    y_op[i, :, :] = Dat[i + 100:i + 115, :]

# Save arrays to a file
np.save('x_in3.npy', x_in)
np.save('y_op3.npy', y_op)

# Save the code as a text file
code = """
import os
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

# Save the current working directory
original_directory = os.getcwd()

# Change the working directory to the desired location
os.chdir(r"C:\\Users\\Aniket\\Desktop\\INTENTION")

# Code to load data and process it
cd = os.getcwd()
print(cd)
items = os.listdir(cd)
print(items)
path = os.path.join(cd, "U003_test_intention.csv")
df1 = pd.read_csv(path)
print(df1.head(5))
print(df1.info())
Gyro_Y = df1.iloc[:, [1, 4, 7, 10, 13]]
Dat = Gyro_Y.values
print(Gyro_Y.head())
print(Dat.shape)
print(Dat)

# windowed output shape [m x o] where m=Sample-(window+output)+1
# and windowed input shape will be [mxw].
Sample = Gyro_Y.shape[0]
print(Sample)
window = 100
output = 15
m = Sample - (window + output) + 1
import numpy as np

# taking window input as 100 and window ouput as 15 for sample=m
x_in = np.zeros((m, 100, 5))
y_op = np.zeros((m, 15, 5))

for i in range(m):
    x_in[i, :, :] = Dat[i:i + 100, :]
    y_op[i, :, :] = Dat[i + 100:i + 115, :]

# Save arrays to a file
np.save('x_in3.npy', x_in)
np.save('y_op3.npy', y_op)
"""

# Specify the zip file name
zip_filename = "code_and_data.zip"

# Create a ZipFile object in write mode
with ZipFile(zip_filename, 'w') as zip:
    # Add the code as a text file to the zip file
    zip.writestr("code.txt", code)

# Change the working directory back to the original directory
os.chdir(original_directory)

# Print a message indicating that the zip file has been created
print(f"Zip file '{zip_filename}' created successfully.")


C:\Users\Aniket\Desktop\INTENTION
['arrays.npz', 'code_and_data.zip', 'max_m.npy', 'max_m_ML.npy', 'min_m.npy', 'min_m_ML.npy', 'U001_test_intention.csv', 'U001_train_intention.csv', 'U001_val_intention.csv', 'U002_test_intention.csv', 'U002_train_intention.csv', 'U002_val_intention.csv', 'U003_test_intention.csv', 'U003_train_intention.csv', 'U003_val_intention.csv', 'U004_test_intention.csv', 'U004_train_intention.csv', 'U004_val_intention.csv', 'U005_test_intention.csv', 'U005_train_intention.csv', 'U005_val_intention.csv', 'U006_test_intention.csv', 'U006_train_intention.csv', 'U006_val_intention.csv', 'U007_test_intention.csv', 'U007_train_intention.csv', 'U007_val_intention.csv', 'U008_test_intention.csv', 'U008_train_intention.csv', 'U008_val_intention.csv', 'U009_test_intention.csv', 'U009_train_intention.csv', 'U009_val_intention.csv', 'U010_test_intention.csv', 'U010_train_intention.csv', 'U010_val_intention.csv', 'U011_test_intention.csv', 'U011_train_intention.csv', 'U011_v