In [1]:
import os
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [2]:
cd=os.getcwd()
print(cd)


C:\Users\Aniket


In [3]:
os.chdir(r"C:\Users\Aniket\Desktop\INTENTION")

In [4]:
cd=os.getcwd()
print(cd)

C:\Users\Aniket\Desktop\INTENTION


In [5]:
items=os.listdir(cd)
print(items)

['arrays.npz', 'U001_test_intention.csv', 'U001_train_intention.csv', 'U001_val_intention.csv', 'U002_test_intention.csv', 'U002_train_intention.csv', 'U002_val_intention.csv', 'U003_test_intention.csv', 'U003_train_intention.csv', 'U003_val_intention.csv', 'U004_test_intention.csv', 'U004_train_intention.csv', 'U004_val_intention.csv', 'U005_test_intention.csv', 'U005_train_intention.csv', 'U005_val_intention.csv', 'U006_test_intention.csv', 'U006_train_intention.csv', 'U006_val_intention.csv', 'U007_test_intention.csv', 'U007_train_intention.csv', 'U007_val_intention.csv', 'U008_test_intention.csv', 'U008_train_intention.csv', 'U008_val_intention.csv', 'U009_test_intention.csv', 'U009_train_intention.csv', 'U009_val_intention.csv', 'U010_test_intention.csv', 'U010_train_intention.csv', 'U010_val_intention.csv', 'U011_test_intention.csv', 'U011_train_intention.csv', 'U011_val_intention.csv', 'U012_test_intention.csv', 'U012_train_intention.csv', 'U012_val_intention.csv', 'x_in.npy', '

In [6]:
path=os.path.join(cd,"U003_train_intention.csv")
df1=pd.read_csv(path)
print(df1.head(5))

   Axel_X_C9  Axel_Y_C9  Axel_Z_C9  Gyro_X_C9  Gyro_Y_C9  Gyro_Z_C9  \
0   8.397011  -3.644112   0.232962  -0.434916   1.304868  -0.173815   
1   8.258917  -3.225936   0.303866  -0.306817   1.265252  -0.212189   
2   8.254112  -2.392820   1.216174  -0.278282   1.190625  -0.227871   
3   8.440770  -1.882961   1.941144  -0.334222   1.102515  -0.233489   
4   8.619517  -1.893684   1.771586  -0.383854   1.071451  -0.220163   

   Axel_X_3B  Axel_Y_3B  Axel_Z_3B  Gyro_X_3B  ...  Gyro_X_B6  Gyro_Y_B6  \
0   8.286073  -1.697515  -4.744943  -0.626845  ...   0.234055  -0.068299   
1   8.187632  -1.648853  -4.594968  -0.632008  ...   0.235893  -0.068770   
2   8.154153  -1.716727  -4.494684  -0.643998  ...   0.218763  -0.065580   
3   8.182753  -1.807217  -4.573571  -0.669550  ...   0.194553  -0.067712   
4   8.169554  -1.780202  -4.607637  -0.679056  ...   0.161030  -0.070543   

   Gyro_Z_B6  Axel_X_BB  Axel_Y_BB  Axel_Z_BB  Gyro_X_BB  Gyro_Y_BB  \
0  -0.044859   7.783253  -5.767363  -0.073932

In [7]:
print(df1.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 98095 entries, 0 to 98094
Data columns (total 31 columns):
 #   Column     Non-Null Count  Dtype  
---  ------     --------------  -----  
 0   Axel_X_C9  98095 non-null  float64
 1   Axel_Y_C9  98095 non-null  float64
 2   Axel_Z_C9  98095 non-null  float64
 3   Gyro_X_C9  98095 non-null  float64
 4   Gyro_Y_C9  98095 non-null  float64
 5   Gyro_Z_C9  98095 non-null  float64
 6   Axel_X_3B  98095 non-null  float64
 7   Axel_Y_3B  98095 non-null  float64
 8   Axel_Z_3B  98095 non-null  float64
 9   Gyro_X_3B  98095 non-null  float64
 10  Gyro_Y_3B  98095 non-null  float64
 11  Gyro_Z_3B  98095 non-null  float64
 12  Axel_X_B5  98095 non-null  float64
 13  Axel_Y_B5  98095 non-null  float64
 14  Axel_Z_B5  98095 non-null  float64
 15  Gyro_X_B5  98095 non-null  float64
 16  Gyro_Y_B5  98095 non-null  float64
 17  Gyro_Z_B5  98095 non-null  float64
 18  Axel_X_B6  98095 non-null  float64
 19  Axel_Y_B6  98095 non-null  float64
 20  Axel_Z

In [8]:
Gyro_Y=df1.iloc[:,[1,4,7,10,13]]
Dat=Gyro_Y.values
print(Gyro_Y.head())
print(Dat.shape)
print(Dat)

   Axel_Y_C9  Gyro_Y_C9  Axel_Y_3B  Gyro_Y_3B  Axel_Y_B5
0  -3.644112   1.304868  -1.697515  -0.175440   3.195290
1  -3.225936   1.265252  -1.648853  -0.187569   3.309237
2  -2.392820   1.190625  -1.716727  -0.220353   3.446816
3  -1.882961   1.102515  -1.807217  -0.258475   3.548115
4  -1.893684   1.071451  -1.780202  -0.278959   3.669381
(98095, 5)
[[-3.644112e+00  1.304868e+00 -1.697515e+00 -1.754400e-01  3.195290e+00]
 [-3.225936e+00  1.265252e+00 -1.648853e+00 -1.875690e-01  3.309237e+00]
 [-2.392820e+00  1.190625e+00 -1.716727e+00 -2.203530e-01  3.446816e+00]
 ...
 [-1.396478e+00  2.157900e-02 -3.510000e-04  2.420000e-03  3.891798e+00]
 [-1.383246e+00  6.386000e-03  4.466700e-02  5.200000e-03  3.925939e+00]
 [-1.436295e+00  1.365700e-02  5.800000e-04  4.098000e-03  3.909755e+00]]


In [9]:
#windowed output shape [m x o] where m=Sample-(window+output)+1
#and windowed input shape will be [mxw].

Sample=Gyro_Y.shape[0]
print(Sample)
window=100
output=15
m=Sample-(window+output)+1

X=np.zeros((m,window))
y=np.zeros((m,output))
print(m)

98095
97981


In [10]:
import numpy as np



#taking window input as 100 and window ouput as 15 for sample=m  
x_in = np.zeros((m,100,5))
y_op = np.zeros((m,15,5))


for i in range(m):
    # Store the first 100 rows
   # print("x_in[i:,:,].shape",x_in[i,:,:].shape,"y_op[i:,:,].shape",y_op[i,:,:].shape,"Dat[i:i+100,:].shape",Dat[i:i+100,:].shape,"Dat[i+100:i+115,:].shape",Dat[i+100:i+115,:].shape)
    x_in[i,:,:] =Dat[i:i+100,:]
    y_op[i,:,:]=Dat[i+100:i+115,:]
     
    
 
    

    # Print the stored arrays
print("x_in:")
print(x_in.shape)
print(y_op.shape)
   

    

 




x_in:
(97981, 100, 5)
(97981, 15, 5)


In [11]:


# Save arrays to a file
np.save('x_in3.npy',x_in)
np.save('y_op3.npy',y_op)
