In [12]:
import os
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [13]:
cd=os.getcwd()
print(cd)


C:\Users\Aniket\Desktop\INTENTION


In [14]:
os.chdir(r"C:\Users\Aniket\Desktop\INTENTION")

In [15]:
cd=os.getcwd()
print(cd)

C:\Users\Aniket\Desktop\INTENTION


In [16]:
items=os.listdir(cd)
print(items)

['arrays.npz', 'U001_test_intention.csv', 'U001_train_intention.csv', 'U001_val_intention.csv', 'U002_test_intention.csv', 'U002_train_intention.csv', 'U002_val_intention.csv', 'U003_test_intention.csv', 'U003_train_intention.csv', 'U003_val_intention.csv', 'U004_test_intention.csv', 'U004_train_intention.csv', 'U004_val_intention.csv', 'U005_test_intention.csv', 'U005_train_intention.csv', 'U005_val_intention.csv', 'U006_test_intention.csv', 'U006_train_intention.csv', 'U006_val_intention.csv', 'U007_test_intention.csv', 'U007_train_intention.csv', 'U007_val_intention.csv', 'U008_test_intention.csv', 'U008_train_intention.csv', 'U008_val_intention.csv', 'U009_test_intention.csv', 'U009_train_intention.csv', 'U009_val_intention.csv', 'U010_test_intention.csv', 'U010_train_intention.csv', 'U010_val_intention.csv', 'U011_test_intention.csv', 'U011_train_intention.csv', 'U011_val_intention.csv', 'U012_test_intention.csv', 'U012_train_intention.csv', 'U012_val_intention.csv', 'x_in.npy', '

In [19]:
path=os.path.join(cd,"U004_train_intention.csv")
df1=pd.read_csv(path)
print(df1.head(5))

   Axel_X_C9  Axel_Y_C9  Axel_Z_C9  Gyro_X_C9  Gyro_Y_C9  Gyro_Z_C9  \
0   9.791250   0.798973  -1.337485  -0.023598  -0.004568   0.007017   
1   9.784659   0.813663  -1.424187  -0.026498  -0.003917   0.006322   
2   9.762796   0.731088  -1.346973  -0.030940   0.000237   0.008527   
3   9.799435   0.758331  -1.275485  -0.022973  -0.001493   0.007227   
4   9.809200   0.780540  -1.270422  -0.026014   0.015338   0.001974   

   Axel_X_3B  Axel_Y_3B  Axel_Z_3B  Gyro_X_3B  ...  Gyro_X_B6  Gyro_Y_B6  \
0   9.675742   0.821515  -1.699097  -0.032157  ...  -0.023063  -0.051914   
1   9.639933   0.812948  -1.736731  -0.033341  ...  -0.042731  -0.040384   
2   9.625605   0.809624  -1.822501  -0.039761  ...   0.037677  -0.015709   
3   9.656044   0.788008  -1.796520  -0.045149  ...   0.005901  -0.017162   
4   9.686355   0.766080  -1.771218  -0.034042  ...  -0.123810  -0.107134   

   Gyro_Z_B6  Axel_X_BB  Axel_Y_BB  Axel_Z_BB  Gyro_X_BB  Gyro_Y_BB  \
0  -0.062856   8.921052  -3.952897   2.487861

In [20]:
print(df1.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 95724 entries, 0 to 95723
Data columns (total 31 columns):
 #   Column     Non-Null Count  Dtype  
---  ------     --------------  -----  
 0   Axel_X_C9  95724 non-null  float64
 1   Axel_Y_C9  95724 non-null  float64
 2   Axel_Z_C9  95724 non-null  float64
 3   Gyro_X_C9  95724 non-null  float64
 4   Gyro_Y_C9  95724 non-null  float64
 5   Gyro_Z_C9  95724 non-null  float64
 6   Axel_X_3B  95724 non-null  float64
 7   Axel_Y_3B  95724 non-null  float64
 8   Axel_Z_3B  95724 non-null  float64
 9   Gyro_X_3B  95724 non-null  float64
 10  Gyro_Y_3B  95724 non-null  float64
 11  Gyro_Z_3B  95724 non-null  float64
 12  Axel_X_B5  95724 non-null  float64
 13  Axel_Y_B5  95724 non-null  float64
 14  Axel_Z_B5  95724 non-null  float64
 15  Gyro_X_B5  95724 non-null  float64
 16  Gyro_Y_B5  95724 non-null  float64
 17  Gyro_Z_B5  95724 non-null  float64
 18  Axel_X_B6  95724 non-null  float64
 19  Axel_Y_B6  95724 non-null  float64
 20  Axel_Z

In [21]:
Gyro_Y=df1.iloc[:,[1,4,7,10,13]]
Dat=Gyro_Y.values
print(Gyro_Y.head())
print(Dat.shape)
print(Dat)

   Axel_Y_C9  Gyro_Y_C9  Axel_Y_3B  Gyro_Y_3B  Axel_Y_B5
0   0.798973  -0.004568   0.821515   0.022101  -2.849386
1   0.813663  -0.003917   0.812948   0.021002  -2.915650
2   0.731088   0.000237   0.809624   0.018468  -3.117260
3   0.758331  -0.001493   0.788008   0.014510  -3.282451
4   0.780540   0.015338   0.766080   0.014017  -3.385240
(95724, 5)
[[ 7.989730e-01 -4.568000e-03  8.215150e-01  2.210100e-02 -2.849386e+00]
 [ 8.136630e-01 -3.917000e-03  8.129480e-01  2.100200e-02 -2.915650e+00]
 [ 7.310880e-01  2.370000e-04  8.096240e-01  1.846800e-02 -3.117260e+00]
 ...
 [ 1.200743e+00  2.959400e-02  1.211352e+00  1.941500e-02 -3.649502e+00]
 [ 1.187101e+00  3.535000e-02  1.238283e+00  1.797400e-02 -3.654023e+00]
 [ 1.194608e+00  2.767000e-02  1.222463e+00  2.109300e-02 -3.650844e+00]]


In [22]:
#windowed output shape [m x o] where m=Sample-(window+output)+1
#and windowed input shape will be [mxw].

Sample=Gyro_Y.shape[0]
print(Sample)
window=100
output=15
m=Sample-(window+output)+1

X=np.zeros((m,window))
y=np.zeros((m,output))
print(m)

95724
95610


In [23]:
import numpy as np



#taking window input as 100 and window ouput as 15 for sample=m  
x_in = np.zeros((m,100,5))
y_op = np.zeros((m,15,5))


for i in range(m):
    # Store the first 100 rows
   # print("x_in[i:,:,].shape",x_in[i,:,:].shape,"y_op[i:,:,].shape",y_op[i,:,:].shape,"Dat[i:i+100,:].shape",Dat[i:i+100,:].shape,"Dat[i+100:i+115,:].shape",Dat[i+100:i+115,:].shape)
    x_in[i,:,:] =Dat[i:i+100,:]
    y_op[i,:,:]=Dat[i+100:i+115,:]
     
    
 
    

    # Print the stored arrays
print("x_in:")
print(x_in.shape)
print(y_op.shape)
   

    

 




x_in:
(95610, 100, 5)
(95610, 15, 5)


In [24]:


# Save arrays to a file
np.save('x_in4.npy',x_in)
np.save('y_op4.npy',y_op)
