In [36]:
import os
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [37]:
cd=os.getcwd()
print(cd)


C:\Users\Aniket\Desktop\INTENTION


In [38]:
os.chdir(r"C:\Users\Aniket\Desktop\INTENTION")

In [39]:
cd=os.getcwd()
print(cd)

C:\Users\Aniket\Desktop\INTENTION


In [40]:
items=os.listdir(cd)
print(items)

['arrays.npz', 'max_m.npy', 'max_m_ML.npy', 'min_m.npy', 'min_m_ML.npy', 'U001_test_intention.csv', 'U001_train_intention.csv', 'U001_val_intention.csv', 'U002_test_intention.csv', 'U002_train_intention.csv', 'U002_val_intention.csv', 'U003_test_intention.csv', 'U003_train_intention.csv', 'U003_val_intention.csv', 'U004_test_intention.csv', 'U004_train_intention.csv', 'U004_val_intention.csv', 'U005_test_intention.csv', 'U005_train_intention.csv', 'U005_val_intention.csv', 'U006_test_intention.csv', 'U006_train_intention.csv', 'U006_val_intention.csv', 'U007_test_intention.csv', 'U007_train_intention.csv', 'U007_val_intention.csv', 'U008_test_intention.csv', 'U008_train_intention.csv', 'U008_val_intention.csv', 'U009_test_intention.csv', 'U009_train_intention.csv', 'U009_val_intention.csv', 'U010_test_intention.csv', 'U010_train_intention.csv', 'U010_val_intention.csv', 'U011_test_intention.csv', 'U011_train_intention.csv', 'U011_val_intention.csv', 'U012_test_intention.csv', 'U012_tra

In [41]:
path=os.path.join(cd,"U004_test_intention.csv")
df1=pd.read_csv(path)
print(df1.head(5))

   Axel_X_C9  Axel_Y_C9  Axel_Z_C9  Gyro_X_C9  Gyro_Y_C9  Gyro_Z_C9  \
0   9.683490   1.675496  -0.368844   0.586777   0.082929  -0.032607   
1   9.701477   1.812494  -0.236138   0.502290   0.067900  -0.027349   
2   9.721047   1.896553  -0.148063   0.411491   0.046924  -0.020485   
3   9.696497   2.001022  -0.115634   0.316226   0.030486  -0.015564   
4   9.719699   2.028287  -0.095515   0.219352   0.014142  -0.009177   

   Axel_X_3B  Axel_Y_3B  Axel_Z_3B  Gyro_X_3B  ...  Gyro_X_B6  Gyro_Y_B6  \
0   9.669623   1.812166  -2.056701   0.651258  ...   0.573477   0.043922   
1   9.693956   1.949499  -2.095716   0.576275  ...   0.541091   0.021158   
2   9.671041   2.096054  -2.212855   0.498142  ...   0.503433   0.008711   
3   9.645506   2.192994  -2.218500   0.401466  ...   0.458970   0.007175   
4   9.620307   2.214576  -2.230414   0.295483  ...   0.409787   0.006670   

   Gyro_Z_B6  Axel_X_BB  Axel_Y_BB  Axel_Z_BB  Gyro_X_BB  Gyro_Y_BB  \
0   0.049294   9.931686  -4.656753   2.903422

In [42]:
print(df1.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 12973 entries, 0 to 12972
Data columns (total 31 columns):
 #   Column     Non-Null Count  Dtype  
---  ------     --------------  -----  
 0   Axel_X_C9  12973 non-null  float64
 1   Axel_Y_C9  12973 non-null  float64
 2   Axel_Z_C9  12973 non-null  float64
 3   Gyro_X_C9  12973 non-null  float64
 4   Gyro_Y_C9  12973 non-null  float64
 5   Gyro_Z_C9  12973 non-null  float64
 6   Axel_X_3B  12973 non-null  float64
 7   Axel_Y_3B  12973 non-null  float64
 8   Axel_Z_3B  12973 non-null  float64
 9   Gyro_X_3B  12973 non-null  float64
 10  Gyro_Y_3B  12973 non-null  float64
 11  Gyro_Z_3B  12973 non-null  float64
 12  Axel_X_B5  12973 non-null  float64
 13  Axel_Y_B5  12973 non-null  float64
 14  Axel_Z_B5  12973 non-null  float64
 15  Gyro_X_B5  12973 non-null  float64
 16  Gyro_Y_B5  12973 non-null  float64
 17  Gyro_Z_B5  12973 non-null  float64
 18  Axel_X_B6  12973 non-null  float64
 19  Axel_Y_B6  12973 non-null  float64
 20  Axel_Z

In [43]:
Gyro_Y=df1.iloc[:,[1,4,7,10,13]]
Dat=Gyro_Y.values
print(Gyro_Y.head())
print(Dat.shape)
print(Dat)

   Axel_Y_C9  Gyro_Y_C9  Axel_Y_3B  Gyro_Y_3B  Axel_Y_B5
0   1.675496   0.082929   1.812166   0.022406   0.122514
1   1.812494   0.067900   1.949499   0.024122  -0.159534
2   1.896553   0.046924   2.096054   0.019737  -0.353688
3   2.001022   0.030486   2.192994   0.020528  -0.583438
4   2.028287   0.014142   2.214576   0.015391  -0.276590
(12973, 5)
[[ 1.675496  0.082929  1.812166  0.022406  0.122514]
 [ 1.812494  0.0679    1.949499  0.024122 -0.159534]
 [ 1.896553  0.046924  2.096054  0.019737 -0.353688]
 ...
 [ 0.760044  0.008452  0.842588  0.031058 -2.685165]
 [ 0.751186  0.011914  0.828441  0.031711 -2.664336]
 [ 0.745463  0.010035  0.840828  0.029004 -2.647991]]


In [44]:
#windowed output shape [m x o] where m=Sample-(window+output)+1
#and windowed input shape will be [mxw].

Sample=Gyro_Y.shape[0]
print(Sample)
window=100
output=15
m=Sample-(window+output)+1

X=np.zeros((m,window))
y=np.zeros((m,output))
print(m)

12973
12859


In [45]:
import numpy as np



#taking window input as 100 and window ouput as 15 for sample=m  
x_in = np.zeros((m,100,5))
y_op = np.zeros((m,15,5))


for i in range(m):
    # Store the first 100 rows
   # print("x_in[i:,:,].shape",x_in[i,:,:].shape,"y_op[i:,:,].shape",y_op[i,:,:].shape,"Dat[i:i+100,:].shape",Dat[i:i+100,:].shape,"Dat[i+100:i+115,:].shape",Dat[i+100:i+115,:].shape)
    x_in[i,:,:] =Dat[i:i+100,:]
    y_op[i,:,:]=Dat[i+100:i+115,:]
     
    
 
    

    # Print the stored arrays
print("x_in:")
print(x_in.shape)
print(y_op.shape)
   

    

 




x_in:
(12859, 100, 5)
(12859, 15, 5)


In [46]:


# Save arrays to a file
np.save('x_in4.npy',x_in)
np.save('y_op4.npy',y_op)
