In [27]:
import os
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [28]:
cd=os.getcwd()
print(cd)


C:\Users\Aniket\Desktop\INTENTION


In [29]:
os.chdir(r"C:\Users\Aniket\Desktop\INTENTION")

In [30]:
cd=os.getcwd()
print(cd)

C:\Users\Aniket\Desktop\INTENTION


In [31]:
items=os.listdir(cd)
print(items)

['arrays.npz', 'U001_test_intention.csv', 'U001_train_intention.csv', 'U001_val_intention.csv', 'U002_test_intention.csv', 'U002_train_intention.csv', 'U002_val_intention.csv', 'U003_test_intention.csv', 'U003_train_intention.csv', 'U003_val_intention.csv', 'U004_test_intention.csv', 'U004_train_intention.csv', 'U004_val_intention.csv', 'U005_test_intention.csv', 'U005_train_intention.csv', 'U005_val_intention.csv', 'U006_test_intention.csv', 'U006_train_intention.csv', 'U006_val_intention.csv', 'U007_test_intention.csv', 'U007_train_intention.csv', 'U007_val_intention.csv', 'U008_test_intention.csv', 'U008_train_intention.csv', 'U008_val_intention.csv', 'U009_test_intention.csv', 'U009_train_intention.csv', 'U009_val_intention.csv', 'U010_test_intention.csv', 'U010_train_intention.csv', 'U010_val_intention.csv', 'U011_test_intention.csv', 'U011_train_intention.csv', 'U011_val_intention.csv', 'U012_test_intention.csv', 'U012_train_intention.csv', 'U012_val_intention.csv', 'x_in.npy', '

In [32]:
path=os.path.join(cd,"U005_train_intention.csv")
df1=pd.read_csv(path)
print(df1.head(5))

   Axel_X_C9  Axel_Y_C9  Axel_Z_C9  Gyro_X_C9  Gyro_Y_C9  Gyro_Z_C9  \
0   9.309346   0.779177  -2.653114  -0.004515  -0.027185  -0.066773   
1   9.286545   0.831112  -2.733128  -0.003122  -0.059088  -0.058523   
2   9.189770   0.808689  -2.817059  -0.000144  -0.098644  -0.051624   
3   9.140257   0.883275  -2.905688   0.001280  -0.133597  -0.043319   
4   9.113244   0.909391  -2.969673  -0.004934  -0.157889  -0.035376   

   Axel_X_3B  Axel_Y_3B  Axel_Z_3B  Gyro_X_3B  ...  Gyro_X_B6  Gyro_Y_B6  \
0   9.863510   0.346955   0.166419  -0.009065  ...   0.120293   0.070444   
1   9.863510   0.376245   0.161806   0.002812  ...   0.115776   0.068589   
2   9.839865   0.428244   0.147253   0.019603  ...   0.113890   0.072356   
3   9.847731   0.520364   0.208532   0.029262  ...   0.101246   0.073774   
4   9.831220   0.539214   0.280031   0.033340  ...   0.083823   0.076310   

   Gyro_Z_B6  Axel_X_BB  Axel_Y_BB  Axel_Z_BB  Gyro_X_BB  Gyro_Y_BB  \
0  -0.076860   8.406933  -0.698972  -3.471952

In [33]:
print(df1.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 77710 entries, 0 to 77709
Data columns (total 31 columns):
 #   Column     Non-Null Count  Dtype  
---  ------     --------------  -----  
 0   Axel_X_C9  77710 non-null  float64
 1   Axel_Y_C9  77710 non-null  float64
 2   Axel_Z_C9  77710 non-null  float64
 3   Gyro_X_C9  77710 non-null  float64
 4   Gyro_Y_C9  77710 non-null  float64
 5   Gyro_Z_C9  77710 non-null  float64
 6   Axel_X_3B  77710 non-null  float64
 7   Axel_Y_3B  77710 non-null  float64
 8   Axel_Z_3B  77710 non-null  float64
 9   Gyro_X_3B  77710 non-null  float64
 10  Gyro_Y_3B  77710 non-null  float64
 11  Gyro_Z_3B  77710 non-null  float64
 12  Axel_X_B5  77710 non-null  float64
 13  Axel_Y_B5  77710 non-null  float64
 14  Axel_Z_B5  77710 non-null  float64
 15  Gyro_X_B5  77710 non-null  float64
 16  Gyro_Y_B5  77710 non-null  float64
 17  Gyro_Z_B5  77710 non-null  float64
 18  Axel_X_B6  77710 non-null  float64
 19  Axel_Y_B6  77710 non-null  float64
 20  Axel_Z

In [34]:
Gyro_Y=df1.iloc[:,[1,4,7,10,13]]
Dat=Gyro_Y.values
print(Gyro_Y.head())
print(Dat.shape)
print(Dat)

   Axel_Y_C9  Gyro_Y_C9  Axel_Y_3B  Gyro_Y_3B  Axel_Y_B5
0   0.779177  -0.027185   0.346955   0.001694   5.122025
1   0.831112  -0.059088   0.376245   0.006824   4.966761
2   0.808689  -0.098644   0.428244   0.011732   4.960805
3   0.883275  -0.133597   0.520364   0.015939   5.044014
4   0.909391  -0.157889   0.539214   0.021085   4.925624
(77710, 5)
[[ 7.791770e-01 -2.718500e-02  3.469550e-01  1.694000e-03  5.122025e+00]
 [ 8.311120e-01 -5.908800e-02  3.762450e-01  6.824000e-03  4.966761e+00]
 [ 8.086890e-01 -9.864400e-02  4.282440e-01  1.173200e-02  4.960805e+00]
 ...
 [-1.771474e+00 -7.769800e-02  2.643086e+00 -2.024570e-01  3.589777e+00]
 [-1.863610e+00 -5.608600e-02  2.437569e+00 -2.295590e-01  4.768867e+00]
 [-1.786507e+00 -5.209300e-02  2.247701e+00 -2.372580e-01  5.542813e+00]]


In [35]:
#windowed output shape [m x o] where m=Sample-(window+output)+1
#and windowed input shape will be [mxw].

Sample=Gyro_Y.shape[0]
print(Sample)
window=100
output=15
m=Sample-(window+output)+1

X=np.zeros((m,window))
y=np.zeros((m,output))
print(m)

77710
77596


In [36]:
import numpy as np



#taking window input as 100 and window ouput as 15 for sample=m  
x_in = np.zeros((m,100,5))
y_op = np.zeros((m,15,5))


for i in range(m):
    # Store the first 100 rows
   # print("x_in[i:,:,].shape",x_in[i,:,:].shape,"y_op[i:,:,].shape",y_op[i,:,:].shape,"Dat[i:i+100,:].shape",Dat[i:i+100,:].shape,"Dat[i+100:i+115,:].shape",Dat[i+100:i+115,:].shape)
    x_in[i,:,:] =Dat[i:i+100,:]
    y_op[i,:,:]=Dat[i+100:i+115,:]
     
    
 
    

    # Print the stored arrays
print("x_in:")
print(x_in.shape)
print(y_op.shape)
   

    

 




x_in:
(77596, 100, 5)
(77596, 15, 5)


In [37]:


# Save arrays to a file
np.save('x_in5.npy',x_in)
np.save('y_op5.npy',y_op)
