In [47]:
import os
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [48]:
cd=os.getcwd()
print(cd)


C:\Users\Aniket\Desktop\INTENTION


In [49]:
os.chdir(r"C:\Users\Aniket\Desktop\INTENTION")

In [50]:
cd=os.getcwd()
print(cd)

C:\Users\Aniket\Desktop\INTENTION


In [40]:
items=os.listdir(cd)
print(items)

['arrays.npz', 'max_m.npy', 'max_m_ML.npy', 'min_m.npy', 'min_m_ML.npy', 'U001_test_intention.csv', 'U001_train_intention.csv', 'U001_val_intention.csv', 'U002_test_intention.csv', 'U002_train_intention.csv', 'U002_val_intention.csv', 'U003_test_intention.csv', 'U003_train_intention.csv', 'U003_val_intention.csv', 'U004_test_intention.csv', 'U004_train_intention.csv', 'U004_val_intention.csv', 'U005_test_intention.csv', 'U005_train_intention.csv', 'U005_val_intention.csv', 'U006_test_intention.csv', 'U006_train_intention.csv', 'U006_val_intention.csv', 'U007_test_intention.csv', 'U007_train_intention.csv', 'U007_val_intention.csv', 'U008_test_intention.csv', 'U008_train_intention.csv', 'U008_val_intention.csv', 'U009_test_intention.csv', 'U009_train_intention.csv', 'U009_val_intention.csv', 'U010_test_intention.csv', 'U010_train_intention.csv', 'U010_val_intention.csv', 'U011_test_intention.csv', 'U011_train_intention.csv', 'U011_val_intention.csv', 'U012_test_intention.csv', 'U012_tra

In [51]:
path=os.path.join(cd,"U005_test_intention.csv")
df1=pd.read_csv(path)
print(df1.head(5))

   Axel_X_C9  Axel_Y_C9  Axel_Z_C9  Gyro_X_C9  Gyro_Y_C9  Gyro_Z_C9  \
0   9.599294  -0.136510  -2.250159  -0.012207   0.012201   0.001583   
1   9.599640  -0.111911  -2.248318  -0.018309   0.015258   0.001578   
2   9.624335  -0.136178  -2.247180  -0.018320   0.013716   0.003087   
3   9.624749  -0.111550  -2.245040  -0.021357   0.019839   0.001610   
4   9.649220  -0.136311  -2.219056  -0.021368   0.018296   0.003119   

   Axel_X_3B  Axel_Y_3B  Axel_Z_3B  Gyro_X_3B  ...  Gyro_X_B6  Gyro_Y_B6  \
0   9.811836   0.252189  -0.946014  -0.010775  ...  -0.062609  -0.068588   
1   9.813377   0.252356  -0.969081  -0.015398  ...  -0.028217  -0.035672   
2   9.787745   0.251842  -0.944588  -0.018361  ...   0.026480  -0.023655   
3   9.790725   0.252749  -0.991794  -0.013741  ...   0.041738  -0.023299   
4   9.813832   0.252555  -0.964409  -0.006071  ...   0.014730  -0.045438   

   Gyro_Z_B6  Axel_X_BB  Axel_Y_BB  Axel_Z_BB  Gyro_X_BB  Gyro_Y_BB  \
0  -0.003491   9.316166  -0.615353  -1.994596

In [52]:
print(df1.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 13439 entries, 0 to 13438
Data columns (total 31 columns):
 #   Column     Non-Null Count  Dtype  
---  ------     --------------  -----  
 0   Axel_X_C9  13439 non-null  float64
 1   Axel_Y_C9  13439 non-null  float64
 2   Axel_Z_C9  13439 non-null  float64
 3   Gyro_X_C9  13439 non-null  float64
 4   Gyro_Y_C9  13439 non-null  float64
 5   Gyro_Z_C9  13439 non-null  float64
 6   Axel_X_3B  13439 non-null  float64
 7   Axel_Y_3B  13439 non-null  float64
 8   Axel_Z_3B  13439 non-null  float64
 9   Gyro_X_3B  13439 non-null  float64
 10  Gyro_Y_3B  13439 non-null  float64
 11  Gyro_Z_3B  13439 non-null  float64
 12  Axel_X_B5  13439 non-null  float64
 13  Axel_Y_B5  13439 non-null  float64
 14  Axel_Z_B5  13439 non-null  float64
 15  Gyro_X_B5  13439 non-null  float64
 16  Gyro_Y_B5  13439 non-null  float64
 17  Gyro_Z_B5  13439 non-null  float64
 18  Axel_X_B6  13439 non-null  float64
 19  Axel_Y_B6  13439 non-null  float64
 20  Axel_Z

In [53]:
Gyro_Y=df1.iloc[:,[1,4,7,10,13]]
Dat=Gyro_Y.values
print(Gyro_Y.head())
print(Dat.shape)
print(Dat)

   Axel_Y_C9  Gyro_Y_C9  Axel_Y_3B  Gyro_Y_3B  Axel_Y_B5
0  -0.136510   0.012201   0.252189   0.010656   3.782733
1  -0.111911   0.015258   0.252356   0.015222   3.846588
2  -0.136178   0.013716   0.251842   0.015245   3.937310
3  -0.111550   0.019839   0.252749   0.015259   3.967249
4  -0.136311   0.018296   0.252555   0.016801   4.042872
(13439, 5)
[[-1.365100e-01  1.220100e-02  2.521890e-01  1.065600e-02  3.782733e+00]
 [-1.119110e-01  1.525800e-02  2.523560e-01  1.522200e-02  3.846588e+00]
 [-1.361780e-01  1.371600e-02  2.518420e-01  1.524500e-02  3.937310e+00]
 ...
 [ 4.935190e-01  1.813730e-01 -1.499399e+00 -2.633400e-02  5.558531e+00]
 [ 6.793490e-01  2.421500e-01 -1.458658e+00 -1.170000e-04  5.569760e+00]
 [ 8.500580e-01  3.285340e-01 -1.352617e+00  1.558200e-02  5.390585e+00]]


In [54]:
#windowed output shape [m x o] where m=Sample-(window+output)+1
#and windowed input shape will be [mxw].

Sample=Gyro_Y.shape[0]
print(Sample)
window=100
output=15
m=Sample-(window+output)+1

X=np.zeros((m,window))
y=np.zeros((m,output))
print(m)

13439
13325


In [55]:
import numpy as np



#taking window input as 100 and window ouput as 15 for sample=m  
x_in = np.zeros((m,100,5))
y_op = np.zeros((m,15,5))


for i in range(m):
    # Store the first 100 rows
   # print("x_in[i:,:,].shape",x_in[i,:,:].shape,"y_op[i:,:,].shape",y_op[i,:,:].shape,"Dat[i:i+100,:].shape",Dat[i:i+100,:].shape,"Dat[i+100:i+115,:].shape",Dat[i+100:i+115,:].shape)
    x_in[i,:,:] =Dat[i:i+100,:]
    y_op[i,:,:]=Dat[i+100:i+115,:]
     
    
 
    

    # Print the stored arrays
print("x_in:")
print(x_in.shape)
print(y_op.shape)
   

    

 




x_in:
(13325, 100, 5)
(13325, 15, 5)


In [56]:


# Save arrays to a file
np.save('x_in5.npy',x_in)
np.save('y_op5.npy',y_op)
