In [57]:
import os
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [58]:
cd=os.getcwd()
print(cd)


C:\Users\Aniket\Desktop\INTENTION


In [59]:
os.chdir(r"C:\Users\Aniket\Desktop\INTENTION")

In [60]:
cd=os.getcwd()
print(cd)

C:\Users\Aniket\Desktop\INTENTION


In [61]:
items=os.listdir(cd)
print(items)

['arrays.npz', 'max_m.npy', 'max_m_ML.npy', 'min_m.npy', 'min_m_ML.npy', 'U001_test_intention.csv', 'U001_train_intention.csv', 'U001_val_intention.csv', 'U002_test_intention.csv', 'U002_train_intention.csv', 'U002_val_intention.csv', 'U003_test_intention.csv', 'U003_train_intention.csv', 'U003_val_intention.csv', 'U004_test_intention.csv', 'U004_train_intention.csv', 'U004_val_intention.csv', 'U005_test_intention.csv', 'U005_train_intention.csv', 'U005_val_intention.csv', 'U006_test_intention.csv', 'U006_train_intention.csv', 'U006_val_intention.csv', 'U007_test_intention.csv', 'U007_train_intention.csv', 'U007_val_intention.csv', 'U008_test_intention.csv', 'U008_train_intention.csv', 'U008_val_intention.csv', 'U009_test_intention.csv', 'U009_train_intention.csv', 'U009_val_intention.csv', 'U010_test_intention.csv', 'U010_train_intention.csv', 'U010_val_intention.csv', 'U011_test_intention.csv', 'U011_train_intention.csv', 'U011_val_intention.csv', 'U012_test_intention.csv', 'U012_tra

In [62]:
path=os.path.join(cd,"U006_test_intention.csv")
df1=pd.read_csv(path)
print(df1.head(5))

   Axel_X_C9  Axel_Y_C9  Axel_Z_C9  Gyro_X_C9  Gyro_Y_C9  Gyro_Z_C9  \
0   9.736633  -1.093421  -1.001198   0.004058  -0.006367   0.009223   
1   9.814605  -1.070758  -1.042814   0.001104  -0.004754   0.007595   
2   9.812282  -1.072453  -1.018939  -0.008086  -0.003086   0.008745   
3   9.836481  -1.074191  -1.016890  -0.012624   0.003078   0.010192   
4   9.785650  -1.073981  -0.996498  -0.007767   0.007661   0.005917   

   Axel_X_3B  Axel_Y_3B  Axel_Z_3B  Gyro_X_3B  ...  Gyro_X_B6  Gyro_Y_B6  \
0   9.789070   0.069454  -0.782290   0.006157  ...   0.012852   0.042103   
1   9.793871   0.038283  -0.852972   0.004732  ...   0.008748   0.019909   
2   9.840956   0.065626  -0.828216   0.006258  ...   0.013478   0.018660   
3   9.814945   0.043699  -0.803660   0.001527  ...   0.010550   0.017505   
4   9.860415   0.000125  -0.747673  -0.001527  ...   0.006630   0.026609   

   Gyro_Z_B6  Axel_X_BB  Axel_Y_BB  Axel_Z_BB  Gyro_X_BB  Gyro_Y_BB  \
0  -0.021448   8.809536  -3.176395   4.336789

In [63]:
print(df1.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 15704 entries, 0 to 15703
Data columns (total 31 columns):
 #   Column     Non-Null Count  Dtype  
---  ------     --------------  -----  
 0   Axel_X_C9  15704 non-null  float64
 1   Axel_Y_C9  15704 non-null  float64
 2   Axel_Z_C9  15704 non-null  float64
 3   Gyro_X_C9  15704 non-null  float64
 4   Gyro_Y_C9  15704 non-null  float64
 5   Gyro_Z_C9  15704 non-null  float64
 6   Axel_X_3B  15704 non-null  float64
 7   Axel_Y_3B  15704 non-null  float64
 8   Axel_Z_3B  15704 non-null  float64
 9   Gyro_X_3B  15704 non-null  float64
 10  Gyro_Y_3B  15704 non-null  float64
 11  Gyro_Z_3B  15704 non-null  float64
 12  Axel_X_B5  15704 non-null  float64
 13  Axel_Y_B5  15704 non-null  float64
 14  Axel_Z_B5  15704 non-null  float64
 15  Gyro_X_B5  15704 non-null  float64
 16  Gyro_Y_B5  15704 non-null  float64
 17  Gyro_Z_B5  15704 non-null  float64
 18  Axel_X_B6  15704 non-null  float64
 19  Axel_Y_B6  15704 non-null  float64
 20  Axel_Z

In [64]:
Gyro_Y=df1.iloc[:,[1,4,7,10,13]]
Dat=Gyro_Y.values
print(Gyro_Y.head())
print(Dat.shape)
print(Dat)

   Axel_Y_C9  Gyro_Y_C9  Axel_Y_3B  Gyro_Y_3B  Axel_Y_B5
0  -1.093421  -0.006367   0.069454  -0.004630   2.327948
1  -1.070758  -0.004754   0.038283  -0.001733   2.333000
2  -1.072453  -0.003086   0.065626  -0.004778   2.306310
3  -1.074191   0.003078   0.043699  -0.004570   2.353807
4  -1.073981   0.007661   0.000125  -0.004580   2.365415
(15704, 5)
[[-1.093421e+00 -6.367000e-03  6.945400e-02 -4.630000e-03  2.327948e+00]
 [-1.070758e+00 -4.754000e-03  3.828300e-02 -1.733000e-03  2.333000e+00]
 [-1.072453e+00 -3.086000e-03  6.562600e-02 -4.778000e-03  2.306310e+00]
 ...
 [-3.672260e-01 -2.941000e-03  7.606800e-02 -5.700000e-04  2.242769e+00]
 [-3.177530e-01  1.628000e-03  7.310000e-02  1.642500e-02  2.236202e+00]
 [-2.909700e-01  8.477000e-03  4.310600e-02  2.845300e-02  2.219915e+00]]


In [65]:
#windowed output shape [m x o] where m=Sample-(window+output)+1
#and windowed input shape will be [mxw].

Sample=Gyro_Y.shape[0]
print(Sample)
window=100
output=15
m=Sample-(window+output)+1

X=np.zeros((m,window))
y=np.zeros((m,output))
print(m)

15704
15590


In [66]:
import numpy as np



#taking window input as 100 and window ouput as 15 for sample=m  
x_in = np.zeros((m,100,5))
y_op = np.zeros((m,15,5))


for i in range(m):
    # Store the first 100 rows
   # print("x_in[i:,:,].shape",x_in[i,:,:].shape,"y_op[i:,:,].shape",y_op[i,:,:].shape,"Dat[i:i+100,:].shape",Dat[i:i+100,:].shape,"Dat[i+100:i+115,:].shape",Dat[i+100:i+115,:].shape)
    x_in[i,:,:] =Dat[i:i+100,:]
    y_op[i,:,:]=Dat[i+100:i+115,:]
     
    
 
    

    # Print the stored arrays
print("x_in:")
print(x_in.shape)
print(y_op.shape)
   

    

 




x_in:
(15590, 100, 5)
(15590, 15, 5)


In [67]:


# Save arrays to a file
np.save('x_in6.npy',x_in)
np.save('y_op6.npy',y_op)
