In [49]:
import os
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [50]:
cd=os.getcwd()
print(cd)


C:\Users\Aniket\Desktop\INTENTION


In [51]:
os.chdir(r"C:\Users\Aniket\Desktop\INTENTION")

In [52]:
cd=os.getcwd()
print(cd)

C:\Users\Aniket\Desktop\INTENTION


In [53]:
items=os.listdir(cd)
print(items)

['arrays.npz', 'U001_test_intention.csv', 'U001_train_intention.csv', 'U001_val_intention.csv', 'U002_test_intention.csv', 'U002_train_intention.csv', 'U002_val_intention.csv', 'U003_test_intention.csv', 'U003_train_intention.csv', 'U003_val_intention.csv', 'U004_test_intention.csv', 'U004_train_intention.csv', 'U004_val_intention.csv', 'U005_test_intention.csv', 'U005_train_intention.csv', 'U005_val_intention.csv', 'U006_test_intention.csv', 'U006_train_intention.csv', 'U006_val_intention.csv', 'U007_test_intention.csv', 'U007_train_intention.csv', 'U007_val_intention.csv', 'U008_test_intention.csv', 'U008_train_intention.csv', 'U008_val_intention.csv', 'U009_test_intention.csv', 'U009_train_intention.csv', 'U009_val_intention.csv', 'U010_test_intention.csv', 'U010_train_intention.csv', 'U010_val_intention.csv', 'U011_test_intention.csv', 'U011_train_intention.csv', 'U011_val_intention.csv', 'U012_test_intention.csv', 'U012_train_intention.csv', 'U012_val_intention.csv', 'x_in.npy', '

In [54]:
path=os.path.join(cd,"U007_train_intention.csv")
df1=pd.read_csv(path)
print(df1.head(5))

   Axel_X_C9  Axel_Y_C9  Axel_Z_C9  Gyro_X_C9  Gyro_Y_C9  Gyro_Z_C9  \
0   9.144607   1.573848  -3.009947   0.122414  -0.062383   0.023278   
1   9.034986   1.596146  -3.159209   0.130057  -0.079714   0.008962   
2   8.988805   1.631141  -3.331753   0.122257  -0.101628   0.003151   
3   9.027456   1.771458  -3.412068   0.134703  -0.124289   0.002869   
4   9.207486   1.783120  -3.309806   0.169579  -0.122371   0.010609   

   Axel_X_3B  Axel_Y_3B  Axel_Z_3B  Gyro_X_3B  ...  Gyro_X_B6  Gyro_Y_B6  \
0   8.770732   1.658186   1.144755   0.508820  ...  -0.309304  -0.362423   
1   8.640261   1.873423   1.825183   0.566543  ...  -0.272339  -0.315952   
2   8.685490   1.936615   1.598322   0.610241  ...  -0.234928  -0.285511   
3   8.907596   2.081706   1.000659   0.595501  ...  -0.201415  -0.273113   
4   8.932914   2.071789   0.987541   0.481836  ...  -0.183620  -0.280058   

   Gyro_Z_B6  Axel_X_BB  Axel_Y_BB  Axel_Z_BB  Gyro_X_BB  Gyro_Y_BB  \
0  -0.190853   8.594905  -3.904066   2.342397

In [55]:
print(df1.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 99208 entries, 0 to 99207
Data columns (total 31 columns):
 #   Column     Non-Null Count  Dtype  
---  ------     --------------  -----  
 0   Axel_X_C9  99208 non-null  float64
 1   Axel_Y_C9  99208 non-null  float64
 2   Axel_Z_C9  99208 non-null  float64
 3   Gyro_X_C9  99208 non-null  float64
 4   Gyro_Y_C9  99208 non-null  float64
 5   Gyro_Z_C9  99208 non-null  float64
 6   Axel_X_3B  99208 non-null  float64
 7   Axel_Y_3B  99208 non-null  float64
 8   Axel_Z_3B  99208 non-null  float64
 9   Gyro_X_3B  99208 non-null  float64
 10  Gyro_Y_3B  99208 non-null  float64
 11  Gyro_Z_3B  99208 non-null  float64
 12  Axel_X_B5  99208 non-null  float64
 13  Axel_Y_B5  99208 non-null  float64
 14  Axel_Z_B5  99208 non-null  float64
 15  Gyro_X_B5  99208 non-null  float64
 16  Gyro_Y_B5  99208 non-null  float64
 17  Gyro_Z_B5  99208 non-null  float64
 18  Axel_X_B6  99208 non-null  float64
 19  Axel_Y_B6  99208 non-null  float64
 20  Axel_Z

In [56]:
Gyro_Y=df1.iloc[:,[1,4,7,10,13]]
Dat=Gyro_Y.values
print(Gyro_Y.head())
print(Dat.shape)
print(Dat)

   Axel_Y_C9  Gyro_Y_C9  Axel_Y_3B  Gyro_Y_3B  Axel_Y_B5
0   1.573848  -0.062383   1.658186   1.292294   4.170509
1   1.596146  -0.079714   1.873423   1.132269   4.185423
2   1.631141  -0.101628   1.936615   0.955642   4.186178
3   1.771458  -0.124289   2.081706   0.861179   4.205724
4   1.783120  -0.122371   2.071789   0.784591   4.235793
(99208, 5)
[[ 1.573848 -0.062383  1.658186  1.292294  4.170509]
 [ 1.596146 -0.079714  1.873423  1.132269  4.185423]
 [ 1.631141 -0.101628  1.936615  0.955642  4.186178]
 ...
 [-0.46831   0.006282  3.207399  0.007287  4.098692]
 [-0.468483  0.008728  3.217592  0.010385  4.100524]
 [-0.497344  0.007426  3.227733  0.008836  4.106719]]


In [57]:
#windowed output shape [m x o] where m=Sample-(window+output)+1
#and windowed input shape will be [mxw].

Sample=Gyro_Y.shape[0]
print(Sample)
window=100
output=15
m=Sample-(window+output)+1

X=np.zeros((m,window))
y=np.zeros((m,output))
print(m)

99208
99094


In [58]:
import numpy as np



#taking window input as 100 and window ouput as 15 for sample=m  
x_in = np.zeros((m,100,5))
y_op = np.zeros((m,15,5))


for i in range(m):
    # Store the first 100 rows
   # print("x_in[i:,:,].shape",x_in[i,:,:].shape,"y_op[i:,:,].shape",y_op[i,:,:].shape,"Dat[i:i+100,:].shape",Dat[i:i+100,:].shape,"Dat[i+100:i+115,:].shape",Dat[i+100:i+115,:].shape)
    x_in[i,:,:] =Dat[i:i+100,:]
    y_op[i,:,:]=Dat[i+100:i+115,:]
     
    
 
    

    # Print the stored arrays
print("x_in:")
print(x_in.shape)
print(y_op.shape)
   

    

 




x_in:
(99094, 100, 5)
(99094, 15, 5)


In [59]:


# Save arrays to a file
np.save('x_in7.npy',x_in)
np.save('y_op7.npy',y_op)
