In [68]:
import os
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [69]:
cd=os.getcwd()
print(cd)


C:\Users\Aniket\Desktop\INTENTION


In [70]:
os.chdir(r"C:\Users\Aniket\Desktop\INTENTION")

In [71]:
cd=os.getcwd()
print(cd)

C:\Users\Aniket\Desktop\INTENTION


In [72]:
items=os.listdir(cd)
print(items)

['arrays.npz', 'max_m.npy', 'max_m_ML.npy', 'min_m.npy', 'min_m_ML.npy', 'U001_test_intention.csv', 'U001_train_intention.csv', 'U001_val_intention.csv', 'U002_test_intention.csv', 'U002_train_intention.csv', 'U002_val_intention.csv', 'U003_test_intention.csv', 'U003_train_intention.csv', 'U003_val_intention.csv', 'U004_test_intention.csv', 'U004_train_intention.csv', 'U004_val_intention.csv', 'U005_test_intention.csv', 'U005_train_intention.csv', 'U005_val_intention.csv', 'U006_test_intention.csv', 'U006_train_intention.csv', 'U006_val_intention.csv', 'U007_test_intention.csv', 'U007_train_intention.csv', 'U007_val_intention.csv', 'U008_test_intention.csv', 'U008_train_intention.csv', 'U008_val_intention.csv', 'U009_test_intention.csv', 'U009_train_intention.csv', 'U009_val_intention.csv', 'U010_test_intention.csv', 'U010_train_intention.csv', 'U010_val_intention.csv', 'U011_test_intention.csv', 'U011_train_intention.csv', 'U011_val_intention.csv', 'U012_test_intention.csv', 'U012_tra

In [73]:
path=os.path.join(cd,"U007_test_intention.csv")
df1=pd.read_csv(path)
print(df1.head(5))

   Axel_X_C9  Axel_Y_C9  Axel_Z_C9  Gyro_X_C9  Gyro_Y_C9  Gyro_Z_C9  \
0   9.750894   0.722890  -1.603472  -0.020142  -0.005546  -0.001916   
1   9.780541   0.770625  -1.582306  -0.020099  -0.004019  -0.001915   
2   9.783242   0.770952  -1.558302  -0.003393  -0.002955  -0.004398   
3   9.780466   0.722637  -1.558335   0.005916   0.002901  -0.004920   
4   9.761847   0.723996  -1.506638   0.018227   0.007144  -0.005617   

   Axel_X_3B  Axel_Y_3B  Axel_Z_3B  Gyro_X_3B  ...  Gyro_X_B6  Gyro_Y_B6  \
0   9.447486   2.061993  -1.775126   0.004558  ...   0.029356   0.030624   
1   9.471476   2.059679  -1.824068   0.013721  ...   0.017030   0.025473   
2   9.496099   2.061215  -1.799691   0.015219  ...   0.011953   0.012700   
3   9.471844   2.037052  -1.797708   0.013685  ...   0.021755   0.019849   
4   9.422700   2.060276  -1.822441   0.016735  ...   0.026349   0.023078   

   Gyro_Z_B6  Axel_X_BB  Axel_Y_BB  Axel_Z_BB  Gyro_X_BB  Gyro_Y_BB  \
0  -0.010272   9.192227  -3.510405   1.989262

In [74]:
print(df1.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 12878 entries, 0 to 12877
Data columns (total 31 columns):
 #   Column     Non-Null Count  Dtype  
---  ------     --------------  -----  
 0   Axel_X_C9  12878 non-null  float64
 1   Axel_Y_C9  12878 non-null  float64
 2   Axel_Z_C9  12878 non-null  float64
 3   Gyro_X_C9  12878 non-null  float64
 4   Gyro_Y_C9  12878 non-null  float64
 5   Gyro_Z_C9  12878 non-null  float64
 6   Axel_X_3B  12878 non-null  float64
 7   Axel_Y_3B  12878 non-null  float64
 8   Axel_Z_3B  12878 non-null  float64
 9   Gyro_X_3B  12878 non-null  float64
 10  Gyro_Y_3B  12878 non-null  float64
 11  Gyro_Z_3B  12878 non-null  float64
 12  Axel_X_B5  12878 non-null  float64
 13  Axel_Y_B5  12878 non-null  float64
 14  Axel_Z_B5  12878 non-null  float64
 15  Gyro_X_B5  12878 non-null  float64
 16  Gyro_Y_B5  12878 non-null  float64
 17  Gyro_Z_B5  12878 non-null  float64
 18  Axel_X_B6  12878 non-null  float64
 19  Axel_Y_B6  12878 non-null  float64
 20  Axel_Z

In [75]:
Gyro_Y=df1.iloc[:,[1,4,7,10,13]]
Dat=Gyro_Y.values
print(Gyro_Y.head())
print(Dat.shape)
print(Dat)

   Axel_Y_C9  Gyro_Y_C9  Axel_Y_3B  Gyro_Y_3B  Axel_Y_B5
0   0.722890  -0.005546   2.061993   0.002982   4.042634
1   0.770625  -0.004019   2.059679   0.001480   4.018448
2   0.770952  -0.002955   2.061215   0.009071   4.024536
3   0.722637   0.002901   2.037052   0.007461   4.054556
4   0.723996   0.007144   2.060276   0.010560   4.058364
(12878, 5)
[[ 7.228900e-01 -5.546000e-03  2.061993e+00  2.982000e-03  4.042634e+00]
 [ 7.706250e-01 -4.019000e-03  2.059679e+00  1.480000e-03  4.018448e+00]
 [ 7.709520e-01 -2.955000e-03  2.061215e+00  9.071000e-03  4.024536e+00]
 ...
 [ 4.974810e-01  3.864660e-01  8.809310e-01 -7.221000e-02  3.492950e+00]
 [ 7.873630e-01  3.755320e-01  1.620793e+00 -8.629900e-02  3.673267e+00]
 [ 1.216745e+00  3.481030e-01  2.144914e+00 -1.570690e-01  3.717021e+00]]


In [76]:
#windowed output shape [m x o] where m=Sample-(window+output)+1
#and windowed input shape will be [mxw].

Sample=Gyro_Y.shape[0]
print(Sample)
window=100
output=15
m=Sample-(window+output)+1

X=np.zeros((m,window))
y=np.zeros((m,output))
print(m)

12878
12764


In [77]:
import numpy as np



#taking window input as 100 and window ouput as 15 for sample=m  
x_in = np.zeros((m,100,5))
y_op = np.zeros((m,15,5))


for i in range(m):
    # Store the first 100 rows
   # print("x_in[i:,:,].shape",x_in[i,:,:].shape,"y_op[i:,:,].shape",y_op[i,:,:].shape,"Dat[i:i+100,:].shape",Dat[i:i+100,:].shape,"Dat[i+100:i+115,:].shape",Dat[i+100:i+115,:].shape)
    x_in[i,:,:] =Dat[i:i+100,:]
    y_op[i,:,:]=Dat[i+100:i+115,:]
     
    
 
    

    # Print the stored arrays
print("x_in:")
print(x_in.shape)
print(y_op.shape)
   

    

 




x_in:
(12764, 100, 5)
(12764, 15, 5)


In [78]:


# Save arrays to a file
np.save('x_in7.npy',x_in)
np.save('y_op7.npy',y_op)
