In [79]:
import os
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [80]:
cd=os.getcwd()
print(cd)


C:\Users\Aniket\Desktop\INTENTION


In [81]:
os.chdir(r"C:\Users\Aniket\Desktop\INTENTION")

In [82]:
cd=os.getcwd()
print(cd)

C:\Users\Aniket\Desktop\INTENTION


In [83]:
items=os.listdir(cd)
print(items)

['arrays.npz', 'max_m.npy', 'max_m_ML.npy', 'min_m.npy', 'min_m_ML.npy', 'U001_test_intention.csv', 'U001_train_intention.csv', 'U001_val_intention.csv', 'U002_test_intention.csv', 'U002_train_intention.csv', 'U002_val_intention.csv', 'U003_test_intention.csv', 'U003_train_intention.csv', 'U003_val_intention.csv', 'U004_test_intention.csv', 'U004_train_intention.csv', 'U004_val_intention.csv', 'U005_test_intention.csv', 'U005_train_intention.csv', 'U005_val_intention.csv', 'U006_test_intention.csv', 'U006_train_intention.csv', 'U006_val_intention.csv', 'U007_test_intention.csv', 'U007_train_intention.csv', 'U007_val_intention.csv', 'U008_test_intention.csv', 'U008_train_intention.csv', 'U008_val_intention.csv', 'U009_test_intention.csv', 'U009_train_intention.csv', 'U009_val_intention.csv', 'U010_test_intention.csv', 'U010_train_intention.csv', 'U010_val_intention.csv', 'U011_test_intention.csv', 'U011_train_intention.csv', 'U011_val_intention.csv', 'U012_test_intention.csv', 'U012_tra

In [84]:
path=os.path.join(cd,"U008_test_intention.csv")
df1=pd.read_csv(path)
print(df1.head(5))

   Axel_X_C9  Axel_Y_C9  Axel_Z_C9  Gyro_X_C9  Gyro_Y_C9  Gyro_Z_C9  \
0  10.034722   0.324988   0.722811  -0.007146  -0.015595   0.018032   
1  10.014496   0.338487   0.831110   0.008222   0.004452   0.029784   
2   9.927086   0.425690   0.951048   0.014886   0.029425   0.036468   
3   9.852207   0.437106   0.873035   0.023247   0.051067   0.042929   
4   9.809950   0.447254   0.846668   0.030818   0.063362   0.045618   

   Axel_X_3B  Axel_Y_3B  Axel_Z_3B  Gyro_X_3B  ...  Gyro_X_B6  Gyro_Y_B6  \
0   9.817333   0.492289  -0.957003   0.065813  ...  -0.042413   0.075004   
1   9.840357   0.509801  -0.976496   0.059374  ...  -0.036922   0.073137   
2   9.839791   0.615594  -0.954245   0.058608  ...  -0.038978   0.067054   
3   9.798376   0.662806  -0.917710   0.056158  ...  -0.044556   0.056973   
4   9.793362   0.740359  -0.825847   0.048247  ...  -0.050278   0.046768   

   Gyro_Z_B6  Axel_X_BB  Axel_Y_BB  Axel_Z_BB  Gyro_X_BB  Gyro_Y_BB  \
0  -0.026428   9.575724  -1.869226   2.237882

In [85]:
print(df1.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 16434 entries, 0 to 16433
Data columns (total 31 columns):
 #   Column     Non-Null Count  Dtype  
---  ------     --------------  -----  
 0   Axel_X_C9  16434 non-null  float64
 1   Axel_Y_C9  16434 non-null  float64
 2   Axel_Z_C9  16434 non-null  float64
 3   Gyro_X_C9  16434 non-null  float64
 4   Gyro_Y_C9  16434 non-null  float64
 5   Gyro_Z_C9  16434 non-null  float64
 6   Axel_X_3B  16434 non-null  float64
 7   Axel_Y_3B  16434 non-null  float64
 8   Axel_Z_3B  16434 non-null  float64
 9   Gyro_X_3B  16434 non-null  float64
 10  Gyro_Y_3B  16434 non-null  float64
 11  Gyro_Z_3B  16434 non-null  float64
 12  Axel_X_B5  16434 non-null  float64
 13  Axel_Y_B5  16434 non-null  float64
 14  Axel_Z_B5  16434 non-null  float64
 15  Gyro_X_B5  16434 non-null  float64
 16  Gyro_Y_B5  16434 non-null  float64
 17  Gyro_Z_B5  16434 non-null  float64
 18  Axel_X_B6  16434 non-null  float64
 19  Axel_Y_B6  16434 non-null  float64
 20  Axel_Z

In [86]:
Gyro_Y=df1.iloc[:,[1,4,7,10,13]]
Dat=Gyro_Y.values
print(Gyro_Y.head())
print(Dat.shape)
print(Dat)

   Axel_Y_C9  Gyro_Y_C9  Axel_Y_3B  Gyro_Y_3B  Axel_Y_B5
0   0.324988  -0.015595   0.492289  -0.037425   3.661946
1   0.338487   0.004452   0.509801  -0.041486   3.666967
2   0.425690   0.029425   0.615594  -0.052513   3.737857
3   0.437106   0.051067   0.662806  -0.062311   3.717938
4   0.447254   0.063362   0.740359  -0.067163   3.723499
(16434, 5)
[[ 0.324988 -0.015595  0.492289 -0.037425  3.661946]
 [ 0.338487  0.004452  0.509801 -0.041486  3.666967]
 [ 0.42569   0.029425  0.615594 -0.052513  3.737857]
 ...
 [-0.384974  0.006094  0.617035  0.00539   3.866063]
 [-0.369485  0.009604  0.600653  0.008715  3.973449]
 [-0.383125  0.011971  0.583416  0.009983  3.826566]]


In [87]:
#windowed output shape [m x o] where m=Sample-(window+output)+1
#and windowed input shape will be [mxw].

Sample=Gyro_Y.shape[0]
print(Sample)
window=100
output=15
m=Sample-(window+output)+1

X=np.zeros((m,window))
y=np.zeros((m,output))
print(m)

16434
16320


In [88]:
import numpy as np



#taking window input as 100 and window ouput as 15 for sample=m  
x_in = np.zeros((m,100,5))
y_op = np.zeros((m,15,5))


for i in range(m):
    # Store the first 100 rows
   # print("x_in[i:,:,].shape",x_in[i,:,:].shape,"y_op[i:,:,].shape",y_op[i,:,:].shape,"Dat[i:i+100,:].shape",Dat[i:i+100,:].shape,"Dat[i+100:i+115,:].shape",Dat[i+100:i+115,:].shape)
    x_in[i,:,:] =Dat[i:i+100,:]
    y_op[i,:,:]=Dat[i+100:i+115,:]
     
    
 
    

    # Print the stored arrays
print("x_in:")
print(x_in.shape)
print(y_op.shape)
   

    

 




x_in:
(16320, 100, 5)
(16320, 15, 5)


In [89]:


# Save arrays to a file
np.save('x_in8.npy',x_in)
np.save('y_op8.npy',y_op)
