In [90]:
import os
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [91]:
cd=os.getcwd()
print(cd)


C:\Users\Aniket\Desktop\INTENTION


In [92]:
os.chdir(r"C:\Users\Aniket\Desktop\INTENTION")

In [93]:
cd=os.getcwd()
print(cd)

C:\Users\Aniket\Desktop\INTENTION


In [94]:
items=os.listdir(cd)
print(items)

['arrays.npz', 'max_m.npy', 'max_m_ML.npy', 'min_m.npy', 'min_m_ML.npy', 'U001_test_intention.csv', 'U001_train_intention.csv', 'U001_val_intention.csv', 'U002_test_intention.csv', 'U002_train_intention.csv', 'U002_val_intention.csv', 'U003_test_intention.csv', 'U003_train_intention.csv', 'U003_val_intention.csv', 'U004_test_intention.csv', 'U004_train_intention.csv', 'U004_val_intention.csv', 'U005_test_intention.csv', 'U005_train_intention.csv', 'U005_val_intention.csv', 'U006_test_intention.csv', 'U006_train_intention.csv', 'U006_val_intention.csv', 'U007_test_intention.csv', 'U007_train_intention.csv', 'U007_val_intention.csv', 'U008_test_intention.csv', 'U008_train_intention.csv', 'U008_val_intention.csv', 'U009_test_intention.csv', 'U009_train_intention.csv', 'U009_val_intention.csv', 'U010_test_intention.csv', 'U010_train_intention.csv', 'U010_val_intention.csv', 'U011_test_intention.csv', 'U011_train_intention.csv', 'U011_val_intention.csv', 'U012_test_intention.csv', 'U012_tra

In [95]:
path=os.path.join(cd,"U009_test_intention.csv")
df1=pd.read_csv(path)
print(df1.head(5))

   Axel_X_C9  Axel_Y_C9  Axel_Z_C9  Gyro_X_C9  Gyro_Y_C9  Gyro_Z_C9  \
0   9.805716  -1.292188  -0.533351  -0.004780   0.009180   0.004407   
1   9.761404  -1.289689  -0.564034  -0.006107   0.013830   0.002867   
2   9.755974  -1.340217  -0.540215   0.001280   0.007532   0.004853   
3   9.777711  -1.293986  -0.509525   0.002509   0.004383   0.007947   
4   9.780746  -1.317977  -0.534234   0.001352   0.004501   0.003264   

   Axel_X_3B  Axel_Y_3B  Axel_Z_3B  Gyro_X_3B  ...  Gyro_X_B6  Gyro_Y_B6  \
0   9.656664   1.975358  -0.301980  -0.000013  ...   0.022529   0.016503   
1   9.680856   1.975143  -0.297574   0.001533  ...   0.020462   0.009110   
2   9.625826   1.970346  -0.341177   0.002518  ...   0.015382  -0.009136   
3   9.643860   1.989431  -0.377410   0.001644  ...   0.008974  -0.007808   
4   9.574934   1.986543  -0.411916   0.011106  ...   0.001474  -0.009681   

   Gyro_Z_B6  Axel_X_BB  Axel_Y_BB  Axel_Z_BB  Gyro_X_BB  Gyro_Y_BB  \
0   0.003683   9.402755  -2.626369   2.546914

In [96]:
print(df1.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 15141 entries, 0 to 15140
Data columns (total 31 columns):
 #   Column     Non-Null Count  Dtype  
---  ------     --------------  -----  
 0   Axel_X_C9  15141 non-null  float64
 1   Axel_Y_C9  15141 non-null  float64
 2   Axel_Z_C9  15141 non-null  float64
 3   Gyro_X_C9  15141 non-null  float64
 4   Gyro_Y_C9  15141 non-null  float64
 5   Gyro_Z_C9  15141 non-null  float64
 6   Axel_X_3B  15141 non-null  float64
 7   Axel_Y_3B  15141 non-null  float64
 8   Axel_Z_3B  15141 non-null  float64
 9   Gyro_X_3B  15141 non-null  float64
 10  Gyro_Y_3B  15141 non-null  float64
 11  Gyro_Z_3B  15141 non-null  float64
 12  Axel_X_B5  15141 non-null  float64
 13  Axel_Y_B5  15141 non-null  float64
 14  Axel_Z_B5  15141 non-null  float64
 15  Gyro_X_B5  15141 non-null  float64
 16  Gyro_Y_B5  15141 non-null  float64
 17  Gyro_Z_B5  15141 non-null  float64
 18  Axel_X_B6  15141 non-null  float64
 19  Axel_Y_B6  15141 non-null  float64
 20  Axel_Z

In [97]:
Gyro_Y=df1.iloc[:,[1,4,7,10,13]]
Dat=Gyro_Y.values
print(Gyro_Y.head())
print(Dat.shape)
print(Dat)

   Axel_Y_C9  Gyro_Y_C9  Axel_Y_3B  Gyro_Y_3B  Axel_Y_B5
0  -1.292188   0.009180   1.975358   0.007740   2.218227
1  -1.289689   0.013830   1.975143   0.009262   2.179171
2  -1.340217   0.007532   1.970346   0.009042   2.216383
3  -1.293986   0.004383   1.989431   0.009153   2.270430
4  -1.317977   0.004501   1.986543  -0.001990   2.305136
(15141, 5)
[[-1.292188  0.00918   1.975358  0.00774   2.218227]
 [-1.289689  0.01383   1.975143  0.009262  2.179171]
 [-1.340217  0.007532  1.970346  0.009042  2.216383]
 ...
 [-2.233562  0.014739  1.774046  0.028871  1.590331]
 [-2.219847  0.016331  1.736958  0.021651  1.560459]
 [-2.208558  0.01977   1.777328  0.01999   1.589826]]


In [98]:
#windowed output shape [m x o] where m=Sample-(window+output)+1
#and windowed input shape will be [mxw].

Sample=Gyro_Y.shape[0]
print(Sample)
window=100
output=15
m=Sample-(window+output)+1

X=np.zeros((m,window))
y=np.zeros((m,output))
print(m)

15141
15027


In [99]:
import numpy as np



#taking window input as 100 and window ouput as 15 for sample=m  
x_in = np.zeros((m,100,5))
y_op = np.zeros((m,15,5))


for i in range(m):
    # Store the first 100 rows
   # print("x_in[i:,:,].shape",x_in[i,:,:].shape,"y_op[i:,:,].shape",y_op[i,:,:].shape,"Dat[i:i+100,:].shape",Dat[i:i+100,:].shape,"Dat[i+100:i+115,:].shape",Dat[i+100:i+115,:].shape)
    x_in[i,:,:] =Dat[i:i+100,:]
    y_op[i,:,:]=Dat[i+100:i+115,:]
     
    
 
    

    # Print the stored arrays
print("x_in:")
print(x_in.shape)
print(y_op.shape)
   

    

 




x_in:
(15027, 100, 5)
(15027, 15, 5)


In [100]:


# Save arrays to a file
np.save('x_in9.npy',x_in)
np.save('y_op9.npy',y_op)
