In [60]:
import os
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [61]:
cd=os.getcwd()
print(cd)


C:\Users\Aniket\Desktop\INTENTION


In [62]:
os.chdir(r"C:\Users\Aniket\Desktop\INTENTION")

In [63]:
cd=os.getcwd()
print(cd)

C:\Users\Aniket\Desktop\INTENTION


In [64]:
items=os.listdir(cd)
print(items)

['arrays.npz', 'U001_test_intention.csv', 'U001_train_intention.csv', 'U001_val_intention.csv', 'U002_test_intention.csv', 'U002_train_intention.csv', 'U002_val_intention.csv', 'U003_test_intention.csv', 'U003_train_intention.csv', 'U003_val_intention.csv', 'U004_test_intention.csv', 'U004_train_intention.csv', 'U004_val_intention.csv', 'U005_test_intention.csv', 'U005_train_intention.csv', 'U005_val_intention.csv', 'U006_test_intention.csv', 'U006_train_intention.csv', 'U006_val_intention.csv', 'U007_test_intention.csv', 'U007_train_intention.csv', 'U007_val_intention.csv', 'U008_test_intention.csv', 'U008_train_intention.csv', 'U008_val_intention.csv', 'U009_test_intention.csv', 'U009_train_intention.csv', 'U009_val_intention.csv', 'U010_test_intention.csv', 'U010_train_intention.csv', 'U010_val_intention.csv', 'U011_test_intention.csv', 'U011_train_intention.csv', 'U011_val_intention.csv', 'U012_test_intention.csv', 'U012_train_intention.csv', 'U012_val_intention.csv', 'x_in.npy', '

In [65]:
path=os.path.join(cd,"U008_train_intention.csv")
df1=pd.read_csv(path)
print(df1.head(5))

   Axel_X_C9  Axel_Y_C9  Axel_Z_C9  Gyro_X_C9  Gyro_Y_C9  Gyro_Z_C9  \
0   9.834513  -0.222748  -0.017160  -0.054571  -0.008453   0.106020   
1   9.815735  -0.144040   0.119557  -0.075463  -0.024534   0.100620   
2   9.814612  -0.075729   0.268725  -0.122038  -0.030189   0.096657   
3   9.820679   0.045152   0.406711  -0.183143  -0.023269   0.097446   
4   9.916372   0.092030   0.416472  -0.251607   0.005274   0.093120   

   Axel_X_3B  Axel_Y_3B  Axel_Z_3B  Gyro_X_3B  ...  Gyro_X_B6  Gyro_Y_B6  \
0   9.671903   0.821166  -0.640402  -0.123489  ...  -0.061236  -0.235297   
1   9.822559   0.670178  -0.645212  -0.116772  ...  -0.073824  -0.234015   
2   9.984182   0.526552  -0.581866  -0.093609  ...  -0.086533  -0.222309   
3   9.992512   0.443045  -0.446665  -0.039963  ...  -0.101781  -0.213251   
4  10.036437   0.377570  -0.283490   0.023524  ...  -0.103429  -0.205970   

   Gyro_Z_B6  Axel_X_BB  Axel_Y_BB  Axel_Z_BB  Gyro_X_BB  Gyro_Y_BB  \
0   0.017084   9.477097  -2.371543   2.826338

In [66]:
print(df1.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 98997 entries, 0 to 98996
Data columns (total 31 columns):
 #   Column     Non-Null Count  Dtype  
---  ------     --------------  -----  
 0   Axel_X_C9  98997 non-null  float64
 1   Axel_Y_C9  98997 non-null  float64
 2   Axel_Z_C9  98997 non-null  float64
 3   Gyro_X_C9  98997 non-null  float64
 4   Gyro_Y_C9  98997 non-null  float64
 5   Gyro_Z_C9  98997 non-null  float64
 6   Axel_X_3B  98997 non-null  float64
 7   Axel_Y_3B  98997 non-null  float64
 8   Axel_Z_3B  98997 non-null  float64
 9   Gyro_X_3B  98997 non-null  float64
 10  Gyro_Y_3B  98997 non-null  float64
 11  Gyro_Z_3B  98997 non-null  float64
 12  Axel_X_B5  98997 non-null  float64
 13  Axel_Y_B5  98997 non-null  float64
 14  Axel_Z_B5  98997 non-null  float64
 15  Gyro_X_B5  98997 non-null  float64
 16  Gyro_Y_B5  98997 non-null  float64
 17  Gyro_Z_B5  98997 non-null  float64
 18  Axel_X_B6  98997 non-null  float64
 19  Axel_Y_B6  98997 non-null  float64
 20  Axel_Z

In [67]:
Gyro_Y=df1.iloc[:,[1,4,7,10,13]]
Dat=Gyro_Y.values
print(Gyro_Y.head())
print(Dat.shape)
print(Dat)

   Axel_Y_C9  Gyro_Y_C9  Axel_Y_3B  Gyro_Y_3B  Axel_Y_B5
0  -0.222748  -0.008453   0.821166   0.009619   3.331442
1  -0.144040  -0.024534   0.670178   0.013394   3.378121
2  -0.075729  -0.030189   0.526552   0.028020   3.355973
3   0.045152  -0.023269   0.443045   0.046857   3.311885
4   0.092030   0.005274   0.377570   0.053635   3.199918
(98997, 5)
[[-0.222748 -0.008453  0.821166  0.009619  3.331442]
 [-0.14404  -0.024534  0.670178  0.013394  3.378121]
 [-0.075729 -0.030189  0.526552  0.02802   3.355973]
 ...
 [-1.298655  0.232649  1.137845  0.07117   3.670335]
 [-1.286987  0.209136  1.257688  0.04935   3.719069]
 [-1.230848  0.200286  1.385844  0.034435  3.514086]]


In [68]:
#windowed output shape [m x o] where m=Sample-(window+output)+1
#and windowed input shape will be [mxw].

Sample=Gyro_Y.shape[0]
print(Sample)
window=100
output=15
m=Sample-(window+output)+1

X=np.zeros((m,window))
y=np.zeros((m,output))
print(m)

98997
98883


In [69]:
import numpy as np



#taking window input as 100 and window ouput as 15 for sample=m  
x_in = np.zeros((m,100,5))
y_op = np.zeros((m,15,5))


for i in range(m):
    # Store the first 100 rows
   # print("x_in[i:,:,].shape",x_in[i,:,:].shape,"y_op[i:,:,].shape",y_op[i,:,:].shape,"Dat[i:i+100,:].shape",Dat[i:i+100,:].shape,"Dat[i+100:i+115,:].shape",Dat[i+100:i+115,:].shape)
    x_in[i,:,:] =Dat[i:i+100,:]
    y_op[i,:,:]=Dat[i+100:i+115,:]
     
    
 
    

    # Print the stored arrays
print("x_in:")
print(x_in.shape)
print(y_op.shape)
   

    

 




x_in:
(98883, 100, 5)
(98883, 15, 5)


In [70]:


# Save arrays to a file
np.save('x_in8.npy',x_in)
np.save('y_op8.npy',y_op)
