In [71]:
import os
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [72]:
cd=os.getcwd()
print(cd)


C:\Users\Aniket\Desktop\INTENTION


In [73]:
os.chdir(r"C:\Users\Aniket\Desktop\INTENTION")

In [74]:
cd=os.getcwd()
print(cd)

C:\Users\Aniket\Desktop\INTENTION


In [75]:
items=os.listdir(cd)
print(items)

['arrays.npz', 'U001_test_intention.csv', 'U001_train_intention.csv', 'U001_val_intention.csv', 'U002_test_intention.csv', 'U002_train_intention.csv', 'U002_val_intention.csv', 'U003_test_intention.csv', 'U003_train_intention.csv', 'U003_val_intention.csv', 'U004_test_intention.csv', 'U004_train_intention.csv', 'U004_val_intention.csv', 'U005_test_intention.csv', 'U005_train_intention.csv', 'U005_val_intention.csv', 'U006_test_intention.csv', 'U006_train_intention.csv', 'U006_val_intention.csv', 'U007_test_intention.csv', 'U007_train_intention.csv', 'U007_val_intention.csv', 'U008_test_intention.csv', 'U008_train_intention.csv', 'U008_val_intention.csv', 'U009_test_intention.csv', 'U009_train_intention.csv', 'U009_val_intention.csv', 'U010_test_intention.csv', 'U010_train_intention.csv', 'U010_val_intention.csv', 'U011_test_intention.csv', 'U011_train_intention.csv', 'U011_val_intention.csv', 'U012_test_intention.csv', 'U012_train_intention.csv', 'U012_val_intention.csv', 'x_in.npy', '

In [76]:
path=os.path.join(cd,"U009_train_intention.csv")
df1=pd.read_csv(path)
print(df1.head(5))

   Axel_X_C9  Axel_Y_C9  Axel_Z_C9  Gyro_X_C9  Gyro_Y_C9  Gyro_Z_C9  \
0   9.856110   1.023643  -0.281951   0.046817  -0.273344  -0.022671   
1   9.774105   1.034285  -0.386320   0.052214  -0.276186  -0.026417   
2   9.765562   1.038173  -0.390561   0.055699  -0.276008  -0.029024   
3   9.777779   0.920142  -0.407188   0.056771  -0.286803  -0.031567   
4   9.806516   0.924666  -0.452770   0.067643  -0.295193  -0.028137   

   Axel_X_3B  Axel_Y_3B  Axel_Z_3B  Gyro_X_3B  ...  Gyro_X_B6  Gyro_Y_B6  \
0   9.914101   0.961165   0.654575  -0.174861  ...   0.043539  -0.088496   
1  10.059575   0.808485   0.849333  -0.152273  ...   0.035656  -0.075539   
2  10.211329   0.670051   1.016547  -0.116625  ...   0.026244  -0.072260   
3  10.281549   0.541180   1.293326  -0.075142  ...   0.012712  -0.086827   
4  10.373435   0.295252   1.541625  -0.037211  ...   0.013656  -0.114490   

   Gyro_Z_B6  Axel_X_BB  Axel_Y_BB  Axel_Z_BB  Gyro_X_BB  Gyro_Y_BB  \
0   0.062219   9.102532  -2.212475   1.030055

In [77]:
print(df1.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 97601 entries, 0 to 97600
Data columns (total 31 columns):
 #   Column     Non-Null Count  Dtype  
---  ------     --------------  -----  
 0   Axel_X_C9  97601 non-null  float64
 1   Axel_Y_C9  97601 non-null  float64
 2   Axel_Z_C9  97601 non-null  float64
 3   Gyro_X_C9  97601 non-null  float64
 4   Gyro_Y_C9  97601 non-null  float64
 5   Gyro_Z_C9  97601 non-null  float64
 6   Axel_X_3B  97601 non-null  float64
 7   Axel_Y_3B  97601 non-null  float64
 8   Axel_Z_3B  97601 non-null  float64
 9   Gyro_X_3B  97601 non-null  float64
 10  Gyro_Y_3B  97601 non-null  float64
 11  Gyro_Z_3B  97601 non-null  float64
 12  Axel_X_B5  97601 non-null  float64
 13  Axel_Y_B5  97601 non-null  float64
 14  Axel_Z_B5  97601 non-null  float64
 15  Gyro_X_B5  97601 non-null  float64
 16  Gyro_Y_B5  97601 non-null  float64
 17  Gyro_Z_B5  97601 non-null  float64
 18  Axel_X_B6  97601 non-null  float64
 19  Axel_Y_B6  97601 non-null  float64
 20  Axel_Z

In [78]:
Gyro_Y=df1.iloc[:,[1,4,7,10,13]]
Dat=Gyro_Y.values
print(Gyro_Y.head())
print(Dat.shape)
print(Dat)

   Axel_Y_C9  Gyro_Y_C9  Axel_Y_3B  Gyro_Y_3B  Axel_Y_B5
0   1.023643  -0.273344   0.961165   0.057996   0.909655
1   1.034285  -0.276186   0.808485   0.086914   0.876790
2   1.038173  -0.276008   0.670051   0.123822   0.840687
3   0.920142  -0.286803   0.541180   0.165899   0.832321
4   0.924666  -0.295193   0.295252   0.209836   0.757823
(97601, 5)
[[ 1.023643e+00 -2.733440e-01  9.611650e-01  5.799600e-02  9.096550e-01]
 [ 1.034285e+00 -2.761860e-01  8.084850e-01  8.691400e-02  8.767900e-01]
 [ 1.038173e+00 -2.760080e-01  6.700510e-01  1.238220e-01  8.406870e-01]
 ...
 [-1.271778e+00 -8.456000e-03  2.566161e+00  1.298500e-02  3.298102e+00]
 [-1.250069e+00 -2.847000e-03  2.612561e+00  1.509900e-02  3.247275e+00]
 [-1.262337e+00  7.299000e-03  2.604430e+00  1.782700e-02  3.330518e+00]]


In [79]:
#windowed output shape [m x o] where m=Sample-(window+output)+1
#and windowed input shape will be [mxw].

Sample=Gyro_Y.shape[0]
print(Sample)
window=100
output=15
m=Sample-(window+output)+1

X=np.zeros((m,window))
y=np.zeros((m,output))
print(m)

97601
97487


In [80]:
import numpy as np



#taking window input as 100 and window ouput as 15 for sample=m  
x_in = np.zeros((m,100,5))
y_op = np.zeros((m,15,5))


for i in range(m):
    # Store the first 100 rows
   # print("x_in[i:,:,].shape",x_in[i,:,:].shape,"y_op[i:,:,].shape",y_op[i,:,:].shape,"Dat[i:i+100,:].shape",Dat[i:i+100,:].shape,"Dat[i+100:i+115,:].shape",Dat[i+100:i+115,:].shape)
    x_in[i,:,:] =Dat[i:i+100,:]
    y_op[i,:,:]=Dat[i+100:i+115,:]
     
    
 
    

    # Print the stored arrays
print("x_in:")
print(x_in.shape)
print(y_op.shape)
   

    

 




x_in:
(97487, 100, 5)
(97487, 15, 5)


In [81]:


# Save arrays to a file
np.save('x_in9.npy',x_in)
np.save('y_op9.npy',y_op)
