In [109]:
import os
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [110]:
cd=os.getcwd()
print(cd)


C:\Users\Aniket\Desktop\INTENTION


In [111]:
os.chdir(r"C:\Users\Aniket\Desktop\INTENTION")

In [112]:
cd=os.getcwd()
print(cd)

C:\Users\Aniket\Desktop\INTENTION


In [113]:
items=os.listdir(cd)
print(items)

['arrays.npz', 'max_m.npy', 'max_m_ML.npy', 'min_m.npy', 'min_m_ML.npy', 'U001_test_intention.csv', 'U001_train_intention.csv', 'U001_val_intention.csv', 'U002_test_intention.csv', 'U002_train_intention.csv', 'U002_val_intention.csv', 'U003_test_intention.csv', 'U003_train_intention.csv', 'U003_val_intention.csv', 'U004_test_intention.csv', 'U004_train_intention.csv', 'U004_val_intention.csv', 'U005_test_intention.csv', 'U005_train_intention.csv', 'U005_val_intention.csv', 'U006_test_intention.csv', 'U006_train_intention.csv', 'U006_val_intention.csv', 'U007_test_intention.csv', 'U007_train_intention.csv', 'U007_val_intention.csv', 'U008_test_intention.csv', 'U008_train_intention.csv', 'U008_val_intention.csv', 'U009_test_intention.csv', 'U009_train_intention.csv', 'U009_val_intention.csv', 'U010_test_intention.csv', 'U010_train_intention.csv', 'U010_val_intention.csv', 'U011_test_intention.csv', 'U011_train_intention.csv', 'U011_val_intention.csv', 'U012_test_intention.csv', 'U012_tra

In [114]:
path=os.path.join(cd,"U010_test_intention.csv")
df1=pd.read_csv(path)
print(df1.head(5))

   Axel_X_C9  Axel_Y_C9  Axel_Z_C9  Gyro_X_C9  Gyro_Y_C9  Gyro_Z_C9  \
0   9.816010  -0.168423  -1.043871  -0.004804   0.004572   0.001648   
1   9.816056  -0.168678  -1.043385   0.002456   0.005380   0.003797   
2   9.862877  -0.163525  -1.070470  -0.008262   0.006230   0.001197   
3   9.839952  -0.173185  -1.045776  -0.004486   0.010056   0.002178   
4   9.834468  -0.193149  -1.058181  -0.006149   0.007486   0.003747   

   Axel_X_3B  Axel_Y_3B  Axel_Z_3B  Gyro_X_3B  ...  Gyro_X_B6  Gyro_Y_B6  \
0   9.606791   1.055685  -1.911412   0.007048  ...   0.015859   0.017710   
1   9.610460   1.035608  -1.866631   0.010511  ...   0.014703   0.018230   
2   9.608760   1.045596  -1.888373   0.008936  ...   0.015285   0.017971   
3   9.608065   1.067830  -1.877702   0.008595  ...   0.014694   0.016923   
4   9.606375   1.078009  -1.899296   0.008870  ...   0.008150   0.015662   

   Gyro_Z_B6  Axel_X_BB  Axel_Y_BB  Axel_Z_BB  Gyro_X_BB  Gyro_Y_BB  \
0  -0.017704   8.489581  -3.097740   5.029782

In [115]:
print(df1.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 25905 entries, 0 to 25904
Data columns (total 31 columns):
 #   Column     Non-Null Count  Dtype  
---  ------     --------------  -----  
 0   Axel_X_C9  25905 non-null  float64
 1   Axel_Y_C9  25905 non-null  float64
 2   Axel_Z_C9  25905 non-null  float64
 3   Gyro_X_C9  25905 non-null  float64
 4   Gyro_Y_C9  25905 non-null  float64
 5   Gyro_Z_C9  25905 non-null  float64
 6   Axel_X_3B  25905 non-null  float64
 7   Axel_Y_3B  25905 non-null  float64
 8   Axel_Z_3B  25905 non-null  float64
 9   Gyro_X_3B  25905 non-null  float64
 10  Gyro_Y_3B  25905 non-null  float64
 11  Gyro_Z_3B  25905 non-null  float64
 12  Axel_X_B5  25905 non-null  float64
 13  Axel_Y_B5  25905 non-null  float64
 14  Axel_Z_B5  25905 non-null  float64
 15  Gyro_X_B5  25905 non-null  float64
 16  Gyro_Y_B5  25905 non-null  float64
 17  Gyro_Z_B5  25905 non-null  float64
 18  Axel_X_B6  25905 non-null  float64
 19  Axel_Y_B6  25905 non-null  float64
 20  Axel_Z

In [116]:
Gyro_Y=df1.iloc[:,[1,4,7,10,13]]
Dat=Gyro_Y.values
print(Gyro_Y.head())
print(Dat.shape)
print(Dat)

   Axel_Y_C9  Gyro_Y_C9  Axel_Y_3B  Gyro_Y_3B  Axel_Y_B5
0  -0.168423   0.004572   1.055685   0.004066   1.075123
1  -0.168678   0.005380   1.035608   0.007565   1.127717
2  -0.163525   0.006230   1.045596   0.003204   1.150499
3  -0.173185   0.010056   1.067830   0.009251   1.123323
4  -0.193149   0.007486   1.078009   0.004487   1.135368
(25905, 5)
[[-1.684230e-01  4.572000e-03  1.055685e+00  4.066000e-03  1.075123e+00]
 [-1.686780e-01  5.380000e-03  1.035608e+00  7.565000e-03  1.127717e+00]
 [-1.635250e-01  6.230000e-03  1.045596e+00  3.204000e-03  1.150499e+00]
 ...
 [-7.790700e-02  1.114700e-02 -1.771592e+00  9.889160e-01  1.068896e+00]
 [-1.089980e-01 -3.440000e-04 -1.505393e+00  1.055144e+00  1.078262e+00]
 [ 2.306900e-02 -4.462000e-03 -1.304119e+00  1.132452e+00  1.100470e+00]]


In [117]:
#windowed output shape [m x o] where m=Sample-(window+output)+1
#and windowed input shape will be [mxw].

Sample=Gyro_Y.shape[0]
print(Sample)
window=100
output=15
m=Sample-(window+output)+1

X=np.zeros((m,window))
y=np.zeros((m,output))
print(m)

25905
25791


In [118]:
import numpy as np



#taking window input as 100 and window ouput as 15 for sample=m  
x_in = np.zeros((m,100,5))
y_op = np.zeros((m,15,5))


for i in range(m):
    # Store the first 100 rows
   # print("x_in[i:,:,].shape",x_in[i,:,:].shape,"y_op[i:,:,].shape",y_op[i,:,:].shape,"Dat[i:i+100,:].shape",Dat[i:i+100,:].shape,"Dat[i+100:i+115,:].shape",Dat[i+100:i+115,:].shape)
    x_in[i,:,:] =Dat[i:i+100,:]
    y_op[i,:,:]=Dat[i+100:i+115,:]
     
    
 
    

    # Print the stored arrays
print("x_in:")
print(x_in.shape)
print(y_op.shape)
   

    

 




x_in:
(25791, 100, 5)
(25791, 15, 5)


In [119]:


# Save arrays to a file
np.save('x_in10.npy',x_in)
np.save('y_op10.npy',y_op)
