In [120]:
import os
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [121]:
cd=os.getcwd()
print(cd)


C:\Users\Aniket\Desktop\INTENTION


In [122]:
os.chdir(r"C:\Users\Aniket\Desktop\INTENTION")

In [123]:
cd=os.getcwd()
print(cd)

C:\Users\Aniket\Desktop\INTENTION


In [124]:
items=os.listdir(cd)
print(items)

['arrays.npz', 'max_m.npy', 'max_m_ML.npy', 'min_m.npy', 'min_m_ML.npy', 'U001_test_intention.csv', 'U001_train_intention.csv', 'U001_val_intention.csv', 'U002_test_intention.csv', 'U002_train_intention.csv', 'U002_val_intention.csv', 'U003_test_intention.csv', 'U003_train_intention.csv', 'U003_val_intention.csv', 'U004_test_intention.csv', 'U004_train_intention.csv', 'U004_val_intention.csv', 'U005_test_intention.csv', 'U005_train_intention.csv', 'U005_val_intention.csv', 'U006_test_intention.csv', 'U006_train_intention.csv', 'U006_val_intention.csv', 'U007_test_intention.csv', 'U007_train_intention.csv', 'U007_val_intention.csv', 'U008_test_intention.csv', 'U008_train_intention.csv', 'U008_val_intention.csv', 'U009_test_intention.csv', 'U009_train_intention.csv', 'U009_val_intention.csv', 'U010_test_intention.csv', 'U010_train_intention.csv', 'U010_val_intention.csv', 'U011_test_intention.csv', 'U011_train_intention.csv', 'U011_val_intention.csv', 'U012_test_intention.csv', 'U012_tra

In [125]:
path=os.path.join(cd,"U011_test_intention.csv")
df1=pd.read_csv(path)
print(df1.head(5))

   Axel_X_C9  Axel_Y_C9  Axel_Z_C9  Gyro_X_C9  Gyro_Y_C9  Gyro_Z_C9  \
0   9.713589  -0.033663  -1.760637  -0.030069   0.019694  -0.012073   
1   9.727557  -0.084089  -1.751376  -0.042461   0.016970  -0.013918   
2   9.726308  -0.144232  -1.704068  -0.052008   0.017649  -0.012037   
3   9.709696  -0.180742  -1.703855  -0.058284   0.012940  -0.014658   
4   9.722746  -0.244987  -1.715124  -0.060743   0.010184  -0.015671   

   Axel_X_3B  Axel_Y_3B  Axel_Z_3B  Gyro_X_3B  ...  Gyro_X_B6  Gyro_Y_B6  \
0   9.594379   1.937624  -1.333950  -0.003372  ...   0.032154  -0.055487   
1   9.587683   1.915791  -1.327601  -0.005239  ...   0.034568  -0.053297   
2   9.615640   1.935570  -1.314398  -0.010366  ...   0.033630  -0.052239   
3   9.570503   1.900749  -1.295906  -0.007590  ...   0.031092  -0.046752   
4   9.602433   1.891472  -1.300939  -0.011812  ...   0.033613  -0.052226   

   Gyro_Z_B6  Axel_X_BB  Axel_Y_BB  Axel_Z_BB  Gyro_X_BB  Gyro_Y_BB  \
0   0.000004   9.209758  -3.437090   1.436980

In [126]:
print(df1.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 16528 entries, 0 to 16527
Data columns (total 31 columns):
 #   Column     Non-Null Count  Dtype  
---  ------     --------------  -----  
 0   Axel_X_C9  16528 non-null  float64
 1   Axel_Y_C9  16528 non-null  float64
 2   Axel_Z_C9  16528 non-null  float64
 3   Gyro_X_C9  16528 non-null  float64
 4   Gyro_Y_C9  16528 non-null  float64
 5   Gyro_Z_C9  16528 non-null  float64
 6   Axel_X_3B  16528 non-null  float64
 7   Axel_Y_3B  16528 non-null  float64
 8   Axel_Z_3B  16528 non-null  float64
 9   Gyro_X_3B  16528 non-null  float64
 10  Gyro_Y_3B  16528 non-null  float64
 11  Gyro_Z_3B  16528 non-null  float64
 12  Axel_X_B5  16528 non-null  float64
 13  Axel_Y_B5  16528 non-null  float64
 14  Axel_Z_B5  16528 non-null  float64
 15  Gyro_X_B5  16528 non-null  float64
 16  Gyro_Y_B5  16528 non-null  float64
 17  Gyro_Z_B5  16528 non-null  float64
 18  Axel_X_B6  16528 non-null  float64
 19  Axel_Y_B6  16528 non-null  float64
 20  Axel_Z

In [127]:
Gyro_Y=df1.iloc[:,[1,4,7,10,13]]
Dat=Gyro_Y.values
print(Gyro_Y.head())
print(Dat.shape)
print(Dat)

   Axel_Y_C9  Gyro_Y_C9  Axel_Y_3B  Gyro_Y_3B  Axel_Y_B5
0  -0.033663   0.019694   1.937624   0.037937   1.864164
1  -0.084089   0.016970   1.915791   0.038231   1.874085
2  -0.144232   0.017649   1.935570   0.040363   1.889299
3  -0.180742   0.012940   1.900749   0.039847   1.911490
4  -0.244987   0.010184   1.891472   0.044331   1.899025
(16528, 5)
[[-3.366300e-02  1.969400e-02  1.937624e+00  3.793700e-02  1.864164e+00]
 [-8.408900e-02  1.697000e-02  1.915791e+00  3.823100e-02  1.874085e+00]
 [-1.442320e-01  1.764900e-02  1.935570e+00  4.036300e-02  1.889299e+00]
 ...
 [-4.195760e-01 -2.860000e-04  1.832592e+00  6.331000e-03  2.461632e+00]
 [-4.198110e-01  5.159000e-03  1.835082e+00  6.761000e-03  2.485237e+00]
 [-4.166340e-01  7.574000e-03  1.839693e+00  8.795000e-03  2.481421e+00]]


In [128]:
#windowed output shape [m x o] where m=Sample-(window+output)+1
#and windowed input shape will be [mxw].

Sample=Gyro_Y.shape[0]
print(Sample)
window=100
output=15
m=Sample-(window+output)+1

X=np.zeros((m,window))
y=np.zeros((m,output))
print(m)

16528
16414


In [129]:
import numpy as np



#taking window input as 100 and window ouput as 15 for sample=m  
x_in = np.zeros((m,100,5))
y_op = np.zeros((m,15,5))


for i in range(m):
    # Store the first 100 rows
   # print("x_in[i:,:,].shape",x_in[i,:,:].shape,"y_op[i:,:,].shape",y_op[i,:,:].shape,"Dat[i:i+100,:].shape",Dat[i:i+100,:].shape,"Dat[i+100:i+115,:].shape",Dat[i+100:i+115,:].shape)
    x_in[i,:,:] =Dat[i:i+100,:]
    y_op[i,:,:]=Dat[i+100:i+115,:]
     
    
 
    

    # Print the stored arrays
print("x_in:")
print(x_in.shape)
print(y_op.shape)
   

    

 




x_in:
(16414, 100, 5)
(16414, 15, 5)


In [130]:


# Save arrays to a file
np.save('x_in11.npy',x_in)
np.save('y_op11.npy',y_op)
