In [82]:
import os
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [83]:
cd=os.getcwd()
print(cd)


C:\Users\Aniket\Desktop\INTENTION


In [84]:
os.chdir(r"C:\Users\Aniket\Desktop\INTENTION")

In [85]:
cd=os.getcwd()
print(cd)

C:\Users\Aniket\Desktop\INTENTION


In [86]:
items=os.listdir(cd)
print(items)

['arrays.npz', 'U001_test_intention.csv', 'U001_train_intention.csv', 'U001_val_intention.csv', 'U002_test_intention.csv', 'U002_train_intention.csv', 'U002_val_intention.csv', 'U003_test_intention.csv', 'U003_train_intention.csv', 'U003_val_intention.csv', 'U004_test_intention.csv', 'U004_train_intention.csv', 'U004_val_intention.csv', 'U005_test_intention.csv', 'U005_train_intention.csv', 'U005_val_intention.csv', 'U006_test_intention.csv', 'U006_train_intention.csv', 'U006_val_intention.csv', 'U007_test_intention.csv', 'U007_train_intention.csv', 'U007_val_intention.csv', 'U008_test_intention.csv', 'U008_train_intention.csv', 'U008_val_intention.csv', 'U009_test_intention.csv', 'U009_train_intention.csv', 'U009_val_intention.csv', 'U010_test_intention.csv', 'U010_train_intention.csv', 'U010_val_intention.csv', 'U011_test_intention.csv', 'U011_train_intention.csv', 'U011_val_intention.csv', 'U012_test_intention.csv', 'U012_train_intention.csv', 'U012_val_intention.csv', 'x_in.npy', '

In [87]:
path=os.path.join(cd,"U010_train_intention.csv")
df1=pd.read_csv(path)
print(df1.head(5))

   Axel_X_C9  Axel_Y_C9  Axel_Z_C9  Gyro_X_C9  Gyro_Y_C9  Gyro_Z_C9  \
0   9.886925  -1.027045  -0.637042   0.149898   0.007059  -0.025742   
1   9.793711  -1.089804  -0.744438   0.173356   0.017515  -0.024442   
2   9.755901  -1.044676  -0.729763   0.191034   0.003291  -0.014067   
3   9.746078  -0.976124  -0.614404   0.202987  -0.022944  -0.011000   
4   9.816432  -0.937496  -0.481693   0.181575  -0.042007  -0.006808   

   Axel_X_3B  Axel_Y_3B  Axel_Z_3B  Gyro_X_3B  ...  Gyro_X_B6  Gyro_Y_B6  \
0   9.870556   0.752292  -1.767731  -0.045117  ...   0.063111   0.002906   
1   9.764399   0.698346  -1.756453  -0.077202  ...   0.083244   0.007958   
2   9.703144   0.735472  -1.674514  -0.094386  ...   0.096736   0.007636   
3   9.701363   0.689902  -1.589968  -0.091056  ...   0.086556   0.014637   
4   9.665071   0.779057  -1.514013  -0.084665  ...   0.084527   0.012447   

   Gyro_Z_B6  Axel_X_BB  Axel_Y_BB  Axel_Z_BB  Gyro_X_BB  Gyro_Y_BB  \
0  -0.053364   9.549052  -2.629604   2.419684

In [88]:
print(df1.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 97811 entries, 0 to 97810
Data columns (total 31 columns):
 #   Column     Non-Null Count  Dtype  
---  ------     --------------  -----  
 0   Axel_X_C9  97811 non-null  float64
 1   Axel_Y_C9  97811 non-null  float64
 2   Axel_Z_C9  97811 non-null  float64
 3   Gyro_X_C9  97811 non-null  float64
 4   Gyro_Y_C9  97811 non-null  float64
 5   Gyro_Z_C9  97811 non-null  float64
 6   Axel_X_3B  97811 non-null  float64
 7   Axel_Y_3B  97811 non-null  float64
 8   Axel_Z_3B  97811 non-null  float64
 9   Gyro_X_3B  97811 non-null  float64
 10  Gyro_Y_3B  97811 non-null  float64
 11  Gyro_Z_3B  97811 non-null  float64
 12  Axel_X_B5  97811 non-null  float64
 13  Axel_Y_B5  97811 non-null  float64
 14  Axel_Z_B5  97811 non-null  float64
 15  Gyro_X_B5  97811 non-null  float64
 16  Gyro_Y_B5  97811 non-null  float64
 17  Gyro_Z_B5  97811 non-null  float64
 18  Axel_X_B6  97811 non-null  float64
 19  Axel_Y_B6  97811 non-null  float64
 20  Axel_Z

In [89]:
Gyro_Y=df1.iloc[:,[1,4,7,10,13]]
Dat=Gyro_Y.values
print(Gyro_Y.head())
print(Dat.shape)
print(Dat)

   Axel_Y_C9  Gyro_Y_C9  Axel_Y_3B  Gyro_Y_3B  Axel_Y_B5
0  -1.027045   0.007059   0.752292  -0.073255   4.593331
1  -1.089804   0.017515   0.698346  -0.085250   5.161860
2  -1.044676   0.003291   0.735472  -0.078009   7.273243
3  -0.976124  -0.022944   0.689902  -0.063289   6.762212
4  -0.937496  -0.042007   0.779057  -0.029406   5.505238
(97811, 5)
[[-1.027045e+00  7.059000e-03  7.522920e-01 -7.325500e-02  4.593331e+00]
 [-1.089804e+00  1.751500e-02  6.983460e-01 -8.525000e-02  5.161860e+00]
 [-1.044676e+00  3.291000e-03  7.354720e-01 -7.800900e-02  7.273243e+00]
 ...
 [ 6.862370e-01  1.467500e-02  2.716987e+00  2.433100e-02  1.009357e+00]
 [ 5.885150e-01  7.955000e-03  2.725310e+00  2.455700e-02  1.021007e+00]
 [ 6.398930e-01  1.233200e-02  2.694815e+00  1.884500e-02  1.016910e+00]]


In [90]:
#windowed output shape [m x o] where m=Sample-(window+output)+1
#and windowed input shape will be [mxw].

Sample=Gyro_Y.shape[0]
print(Sample)
window=100
output=15
m=Sample-(window+output)+1

X=np.zeros((m,window))
y=np.zeros((m,output))
print(m)

97811
97697


In [91]:
import numpy as np



#taking window input as 100 and window ouput as 15 for sample=m  
x_in = np.zeros((m,100,5))
y_op = np.zeros((m,15,5))


for i in range(m):
    # Store the first 100 rows
   # print("x_in[i:,:,].shape",x_in[i,:,:].shape,"y_op[i:,:,].shape",y_op[i,:,:].shape,"Dat[i:i+100,:].shape",Dat[i:i+100,:].shape,"Dat[i+100:i+115,:].shape",Dat[i+100:i+115,:].shape)
    x_in[i,:,:] =Dat[i:i+100,:]
    y_op[i,:,:]=Dat[i+100:i+115,:]
     
    
 
    

    # Print the stored arrays
print("x_in:")
print(x_in.shape)
print(y_op.shape)
   

    

 




x_in:
(97697, 100, 5)
(97697, 15, 5)


In [92]:


# Save arrays to a file
np.save('x_in10.npy',x_in)
np.save('y_op10.npy',y_op)
