In [131]:
import os
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [132]:
cd=os.getcwd()
print(cd)


C:\Users\Aniket\Desktop\INTENTION


In [133]:
os.chdir(r"C:\Users\Aniket\Desktop\INTENTION")

In [134]:
cd=os.getcwd()
print(cd)

C:\Users\Aniket\Desktop\INTENTION


In [135]:
items=os.listdir(cd)
print(items)

['arrays.npz', 'max_m.npy', 'max_m_ML.npy', 'min_m.npy', 'min_m_ML.npy', 'U001_test_intention.csv', 'U001_train_intention.csv', 'U001_val_intention.csv', 'U002_test_intention.csv', 'U002_train_intention.csv', 'U002_val_intention.csv', 'U003_test_intention.csv', 'U003_train_intention.csv', 'U003_val_intention.csv', 'U004_test_intention.csv', 'U004_train_intention.csv', 'U004_val_intention.csv', 'U005_test_intention.csv', 'U005_train_intention.csv', 'U005_val_intention.csv', 'U006_test_intention.csv', 'U006_train_intention.csv', 'U006_val_intention.csv', 'U007_test_intention.csv', 'U007_train_intention.csv', 'U007_val_intention.csv', 'U008_test_intention.csv', 'U008_train_intention.csv', 'U008_val_intention.csv', 'U009_test_intention.csv', 'U009_train_intention.csv', 'U009_val_intention.csv', 'U010_test_intention.csv', 'U010_train_intention.csv', 'U010_val_intention.csv', 'U011_test_intention.csv', 'U011_train_intention.csv', 'U011_val_intention.csv', 'U012_test_intention.csv', 'U012_tra

In [136]:
path=os.path.join(cd,"U012_test_intention.csv")
df1=pd.read_csv(path)
print(df1.head(5))

   Axel_X_C9  Axel_Y_C9  Axel_Z_C9  Gyro_X_C9  Gyro_Y_C9  Gyro_Z_C9  \
0   9.921161   0.115193   0.540733  -0.072230  -0.026907  -0.023113   
1   9.874496   0.072669   0.461152  -0.079592  -0.020399  -0.021943   
2   9.877090   0.098451   0.459627  -0.080916  -0.011132  -0.015913   
3   9.898765   0.072849   0.461055  -0.074589  -0.006870  -0.015633   
4   9.907950   0.097525   0.387833  -0.083544  -0.000279  -0.012998   

   Axel_X_3B  Axel_Y_3B  Axel_Z_3B  Gyro_X_3B  ...  Gyro_X_B6  Gyro_Y_B6  \
0   9.869606  -0.901593   0.215404  -0.062227  ...   0.002986  -0.009976   
1   9.844510  -0.878802   0.226368  -0.060632  ...  -0.000148  -0.007027   
2   9.848441  -0.880445   0.256319  -0.058825  ...  -0.007997  -0.001236   
3   9.820039  -0.881493   0.242137  -0.055757  ...  -0.014194   0.003136   
4   9.795771  -0.883359   0.251959  -0.060476  ...  -0.019183   0.010515   

   Gyro_Z_B6  Axel_X_BB  Axel_Y_BB  Axel_Z_BB  Gyro_X_BB  Gyro_Y_BB  \
0  -0.026104   9.147005  -3.043985  -0.555856

In [137]:
print(df1.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 16160 entries, 0 to 16159
Data columns (total 31 columns):
 #   Column     Non-Null Count  Dtype  
---  ------     --------------  -----  
 0   Axel_X_C9  16160 non-null  float64
 1   Axel_Y_C9  16160 non-null  float64
 2   Axel_Z_C9  16160 non-null  float64
 3   Gyro_X_C9  16160 non-null  float64
 4   Gyro_Y_C9  16160 non-null  float64
 5   Gyro_Z_C9  16160 non-null  float64
 6   Axel_X_3B  16160 non-null  float64
 7   Axel_Y_3B  16160 non-null  float64
 8   Axel_Z_3B  16160 non-null  float64
 9   Gyro_X_3B  16160 non-null  float64
 10  Gyro_Y_3B  16160 non-null  float64
 11  Gyro_Z_3B  16160 non-null  float64
 12  Axel_X_B5  16160 non-null  float64
 13  Axel_Y_B5  16160 non-null  float64
 14  Axel_Z_B5  16160 non-null  float64
 15  Gyro_X_B5  16160 non-null  float64
 16  Gyro_Y_B5  16160 non-null  float64
 17  Gyro_Z_B5  16160 non-null  float64
 18  Axel_X_B6  16160 non-null  float64
 19  Axel_Y_B6  16160 non-null  float64
 20  Axel_Z

In [138]:
Gyro_Y=df1.iloc[:,[1,4,7,10,13]]
Dat=Gyro_Y.values
print(Gyro_Y.head())
print(Dat.shape)
print(Dat)

   Axel_Y_C9  Gyro_Y_C9  Axel_Y_3B  Gyro_Y_3B  Axel_Y_B5
0   0.115193  -0.026907  -0.901593   0.063052   3.444379
1   0.072669  -0.020399  -0.878802   0.066116   3.418722
2   0.098451  -0.011132  -0.880445   0.064560   3.458389
3   0.072849  -0.006870  -0.881493   0.063091   3.464203
4   0.097525  -0.000279  -0.883359   0.064549   3.421811
(16160, 5)
[[ 1.151930e-01 -2.690700e-02 -9.015930e-01  6.305200e-02  3.444379e+00]
 [ 7.266900e-02 -2.039900e-02 -8.788020e-01  6.611600e-02  3.418722e+00]
 [ 9.845100e-02 -1.113200e-02 -8.804450e-01  6.456000e-02  3.458389e+00]
 ...
 [ 1.872300e-01  2.523000e-03 -8.949320e-01  1.066800e-02  3.094897e+00]
 [ 1.970610e-01  6.032000e-03 -9.284070e-01  1.000300e-02  3.087585e+00]
 [ 1.884890e-01  2.692000e-03 -9.154310e-01  6.168000e-03  3.103365e+00]]


In [139]:
#windowed output shape [m x o] where m=Sample-(window+output)+1
#and windowed input shape will be [mxw].

Sample=Gyro_Y.shape[0]
print(Sample)
window=100
output=15
m=Sample-(window+output)+1

X=np.zeros((m,window))
y=np.zeros((m,output))
print(m)

16160
16046


In [140]:
import numpy as np



#taking window input as 100 and window ouput as 15 for sample=m  
x_in = np.zeros((m,100,5))
y_op = np.zeros((m,15,5))


for i in range(m):
    # Store the first 100 rows
   # print("x_in[i:,:,].shape",x_in[i,:,:].shape,"y_op[i:,:,].shape",y_op[i,:,:].shape,"Dat[i:i+100,:].shape",Dat[i:i+100,:].shape,"Dat[i+100:i+115,:].shape",Dat[i+100:i+115,:].shape)
    x_in[i,:,:] =Dat[i:i+100,:]
    y_op[i,:,:]=Dat[i+100:i+115,:]
     
    
 
    

    # Print the stored arrays
print("x_in:")
print(x_in.shape)
print(y_op.shape)
   

    

 




x_in:
(16046, 100, 5)
(16046, 15, 5)


In [141]:


# Save arrays to a file
np.save('x_in12.npy',x_in)
np.save('y_op12.npy',y_op)
