In [1]:
import os
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [2]:
cd=os.getcwd()
print(cd)


C:\Users\Aniket


In [3]:
os.chdir(r"C:\Users\Aniket\Desktop\INTENTION")

In [4]:
cd=os.getcwd()
print(cd)

C:\Users\Aniket\Desktop\INTENTION


In [5]:
items=os.listdir(cd)
print(items)

['arrays.npz', 'max_m.npy', 'max_m_ML.npy', 'min_m.npy', 'min_m_ML.npy', 'U001_test_intention.csv', 'U001_train_intention.csv', 'U001_val_intention.csv', 'U002_test_intention.csv', 'U002_train_intention.csv', 'U002_val_intention.csv', 'U003_test_intention.csv', 'U003_train_intention.csv', 'U003_val_intention.csv', 'U004_test_intention.csv', 'U004_train_intention.csv', 'U004_val_intention.csv', 'U005_test_intention.csv', 'U005_train_intention.csv', 'U005_val_intention.csv', 'U006_test_intention.csv', 'U006_train_intention.csv', 'U006_val_intention.csv', 'U007_test_intention.csv', 'U007_train_intention.csv', 'U007_val_intention.csv', 'U008_test_intention.csv', 'U008_train_intention.csv', 'U008_val_intention.csv', 'U009_test_intention.csv', 'U009_train_intention.csv', 'U009_val_intention.csv', 'U010_test_intention.csv', 'U010_train_intention.csv', 'U010_val_intention.csv', 'U011_test_intention.csv', 'U011_train_intention.csv', 'U011_val_intention.csv', 'U012_test_intention.csv', 'U012_tra

In [6]:
path=os.path.join(cd,"U001_test_intention.csv")
df1=pd.read_csv(path)
print(df1.head(5))

   Gyro_X_C9  Gyro_Y_C9  Gyro_Z_C9  Gyro_X_3B  Gyro_Y_3B  Gyro_Z_3B  \
0  -0.003301   0.003108   0.006429   0.008471  -0.001293  -0.001056   
1  -0.000273   0.002850   0.007587   0.007631  -0.002413  -0.000322   
2   0.003585   0.003493   0.006959   0.008472  -0.001293  -0.001056   
3   0.000052   0.002415   0.011353   0.011868  -0.003059  -0.000849   
4  -0.007158   0.002466   0.007057   0.010763   0.001010  -0.004643   

   Gyro_X_B5  Gyro_Y_B5  Gyro_Z_B5  Gyro_X_B6  Gyro_Y_B6  Gyro_Z_B6  \
0  -0.004435  -0.014313  -0.009454  -0.002486   0.066973  -0.029534   
1  -0.005602  -0.010750  -0.009857  -0.010069   0.076443  -0.025291   
2  -0.008474  -0.012894  -0.012194  -0.013269   0.081873  -0.024645   
3  -0.011794  -0.009761  -0.013167  -0.016492   0.076151  -0.024798   
4  -0.016248  -0.008865  -0.013853  -0.007390   0.070878  -0.023847   

   Gyro_X_BB  Gyro_Y_BB  Gyro_Z_BB  target  
0   0.048590  -0.005188  -0.014915       0  
1   0.045663  -0.002525  -0.011840       0  
2   0.04874

In [7]:
print(df1.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1746 entries, 0 to 1745
Data columns (total 16 columns):
 #   Column     Non-Null Count  Dtype  
---  ------     --------------  -----  
 0   Gyro_X_C9  1746 non-null   float64
 1   Gyro_Y_C9  1746 non-null   float64
 2   Gyro_Z_C9  1746 non-null   float64
 3   Gyro_X_3B  1746 non-null   float64
 4   Gyro_Y_3B  1746 non-null   float64
 5   Gyro_Z_3B  1746 non-null   float64
 6   Gyro_X_B5  1746 non-null   float64
 7   Gyro_Y_B5  1746 non-null   float64
 8   Gyro_Z_B5  1746 non-null   float64
 9   Gyro_X_B6  1746 non-null   float64
 10  Gyro_Y_B6  1746 non-null   float64
 11  Gyro_Z_B6  1746 non-null   float64
 12  Gyro_X_BB  1746 non-null   float64
 13  Gyro_Y_BB  1746 non-null   float64
 14  Gyro_Z_BB  1746 non-null   float64
 15  target     1746 non-null   int64  
dtypes: float64(15), int64(1)
memory usage: 218.4 KB
None


In [8]:
Gyro_Y=df1.iloc[:,[1,4,7,10,13]]
Dat=Gyro_Y.values
print(Gyro_Y.head())
print(Dat.shape)
print(Dat)

   Gyro_Y_C9  Gyro_Y_3B  Gyro_Y_B5  Gyro_Y_B6  Gyro_Y_BB
0   0.003108  -0.001293  -0.014313   0.066973  -0.005188
1   0.002850  -0.002413  -0.010750   0.076443  -0.002525
2   0.003493  -0.001293  -0.012894   0.081873  -0.001826
3   0.002415  -0.003059  -0.009761   0.076151  -0.002256
4   0.002466   0.001010  -0.008865   0.070878  -0.001812
(1746, 5)
[[ 3.108000e-03 -1.293000e-03 -1.431300e-02  6.697300e-02 -5.188000e-03]
 [ 2.850000e-03 -2.413000e-03 -1.075000e-02  7.644300e-02 -2.525000e-03]
 [ 3.493000e-03 -1.293000e-03 -1.289400e-02  8.187300e-02 -1.826000e-03]
 ...
 [-2.063550e+00 -2.161242e+00 -5.731140e-01  2.307875e+00 -3.438970e-01]
 [-1.965258e+00 -1.997112e+00 -5.437530e-01  2.318974e+00 -3.101530e-01]
 [-1.917985e+00 -1.825734e+00 -4.997440e-01  2.357349e+00 -2.694310e-01]]


In [9]:
#windowed output shape [m x o] where m=Sample-(window+output)+1
#and windowed input shape will be [mxw].

Sample=Gyro_Y.shape[0]
print(Sample)
window=100
output=15
m=Sample-(window+output)+1

X=np.zeros((m,window))
y=np.zeros((m,output))
print(m)

1746
1632


In [10]:
import numpy as np



#taking window input as 100 and window ouput as 15 for sample=m  
x_in = np.zeros((m,100,5))
y_op = np.zeros((m,15,5))


for i in range(m):
    # Store the first 100 rows
   # print("x_in[i:,:,].shape",x_in[i,:,:].shape,"y_op[i:,:,].shape",y_op[i,:,:].shape,"Dat[i:i+100,:].shape",Dat[i:i+100,:].shape,"Dat[i+100:i+115,:].shape",Dat[i+100:i+115,:].shape)
    x_in[i,:,:] =Dat[i:i+100,:]
    y_op[i,:,:]=Dat[i+100:i+115,:]
     
    
 
    

    # Print the stored arrays
print("x_in:")
print(x_in.shape)
print(y_op.shape)
   

    

 




x_in:
(1632, 100, 5)
(1632, 15, 5)


In [13]:


# Save arrays to a file
np.save('x_in1.npy',x_in)
np.save('y_op1.npy',y_op)
